// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using Pulumi;

namespace Rocket.Surgery.OnePasswordNativeUnofficial.SoftwareLicense.Inputs
{

    public sealed class OrderSectionArgs : Pulumi.ResourceArgs
    {
        [Input("orderNumber")]
        public Input<string>? OrderNumber { get; set; }

        [Input("orderTotal")]
        public Input<string>? OrderTotal { get; set; }

        [Input("purchaseDate")]
        public Input<string>? PurchaseDate { get; set; }

        public OrderSectionArgs()
        {
        }
    }
}
