#!/bin/bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
# node $SCRIPT_DIR/bin/index.js
dotnet $SCRIPT_DIR/bin/Debug/net8.0/pulumi-resource-one-password-native-unoffical.dll $@
