// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onepassword
{
    [OnepasswordResourceType("onepassword:index:BankAccount")]
    public partial class BankAccount : Pulumi.CustomResource
    {
        /// <summary>
        /// Create a BankAccount resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public BankAccount(string name, BankAccountArgs? args = null, CustomResourceOptions? options = null)
            : base("onepassword:index:BankAccount", name, args ?? new BankAccountArgs(), MakeResourceOptions(options, ""))
        {
        }

        private BankAccount(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("onepassword:index:BankAccount", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing BankAccount resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static BankAccount Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new BankAccount(name, id, options);
        }
    }

    public sealed class BankAccountArgs : Pulumi.ResourceArgs
    {
        [Input("accountNumber")]
        public Input<string>? AccountNumber { get; set; }

        [Input("bankName")]
        public Input<string>? BankName { get; set; }

        [Input("branchInformation")]
        public Input<Pulumi.BankAccount.Section.Inputs.BranchInformation>? BranchInformation { get; set; }

        [Input("iban")]
        public Input<string>? Iban { get; set; }

        [Input("nameOnAccount")]
        public Input<string>? NameOnAccount { get; set; }

        [Input("notes")]
        public Input<string>? Notes { get; set; }

        [Input("pin")]
        public Input<string>? Pin { get; set; }

        [Input("routingNumber")]
        public Input<string>? RoutingNumber { get; set; }

        [Input("swift")]
        public Input<string>? Swift { get; set; }

        [Input("type")]
        public Input<string>? Type { get; set; }

        public BankAccountArgs()
        {
        }
    }
}
