// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onepassword
{
    public static class GetCreditCard
    {
        public static Task<GetCreditCardResult> InvokeAsync(GetCreditCardArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetCreditCardResult>("onepassword:index:GetCreditCard", args ?? new GetCreditCardArgs(), options.WithDefaults());

        public static Output<GetCreditCardResult> Invoke(GetCreditCardInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetCreditCardResult>("onepassword:index:GetCreditCard", args ?? new GetCreditCardInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetCreditCardArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// The title of the item to retrieve. This field will be populated with the title of the item if the item it looked up by its UUID.
        /// </summary>
        [Input("title")]
        public string? Title { get; set; }

        /// <summary>
        /// The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
        /// </summary>
        [Input("uuid")]
        public string? Uuid { get; set; }

        /// <summary>
        /// The UUID of the vault the item is in.
        /// </summary>
        [Input("vault", required: true)]
        public string Vault { get; set; } = null!;

        public GetCreditCardArgs()
        {
        }
    }

    public sealed class GetCreditCardInvokeArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// The title of the item to retrieve. This field will be populated with the title of the item if the item it looked up by its UUID.
        /// </summary>
        [Input("title")]
        public Input<string>? Title { get; set; }

        /// <summary>
        /// The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
        /// </summary>
        [Input("uuid")]
        public Input<string>? Uuid { get; set; }

        /// <summary>
        /// The UUID of the vault the item is in.
        /// </summary>
        [Input("vault", required: true)]
        public Input<string> Vault { get; set; } = null!;

        public GetCreditCardInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetCreditCardResult
    {
        public readonly Pulumi.Onepassword.CreditCard.Outputs.AdditionalDetailsSection? AdditionalDetails;
        public readonly string? CardholderName;
        public readonly string? Category;
        public readonly Pulumi.Onepassword.CreditCard.Outputs.ContactInformationSection? ContactInformation;
        public readonly string? ExpiryDate;
        public readonly ImmutableDictionary<string, Outputs.GetField>? Fields;
        public readonly string? Id;
        public readonly string? Notes;
        public readonly string? Number;
        public readonly ImmutableDictionary<string, Outputs.GetSection>? Sections;
        /// <summary>
        /// An array of strings of the tags assigned to the item.
        /// </summary>
        public readonly ImmutableArray<string> Tags;
        /// <summary>
        /// The title of the item.
        /// </summary>
        public readonly string? Title;
        public readonly string? Type;
        /// <summary>
        /// The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
        /// </summary>
        public readonly string? Uuid;
        public readonly string? ValidFrom;
        /// <summary>
        /// The UUID of the vault the item is in.
        /// </summary>
        public readonly string? Vault;
        public readonly string? VerificationNumber;

        [OutputConstructor]
        private GetCreditCardResult(
            Pulumi.Onepassword.CreditCard.Outputs.AdditionalDetailsSection? additionalDetails,

            string? cardholderName,

            string? category,

            Pulumi.Onepassword.CreditCard.Outputs.ContactInformationSection? contactInformation,

            string? expiryDate,

            ImmutableDictionary<string, Outputs.GetField>? fields,

            string? id,

            string? notes,

            string? number,

            ImmutableDictionary<string, Outputs.GetSection>? sections,

            ImmutableArray<string> tags,

            string? title,

            string? type,

            string? uuid,

            string? validFrom,

            string? vault,

            string? verificationNumber)
        {
            AdditionalDetails = additionalDetails;
            CardholderName = cardholderName;
            Category = category;
            ContactInformation = contactInformation;
            ExpiryDate = expiryDate;
            Fields = fields;
            Id = id;
            Notes = notes;
            Number = number;
            Sections = sections;
            Tags = tags;
            Title = title;
            Type = type;
            Uuid = uuid;
            ValidFrom = validFrom;
            Vault = vault;
            VerificationNumber = verificationNumber;
        }
    }
}
