// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Onepassword
{
    [OnepasswordResourceType("onepassword:index:MedicalRecord")]
    public partial class MedicalRecord : Pulumi.CustomResource
    {
        /// <summary>
        /// Create a MedicalRecord resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public MedicalRecord(string name, MedicalRecordArgs? args = null, CustomResourceOptions? options = null)
            : base("onepassword:index:MedicalRecord", name, args ?? new MedicalRecordArgs(), MakeResourceOptions(options, ""))
        {
        }

        private MedicalRecord(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("onepassword:index:MedicalRecord", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing MedicalRecord resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static MedicalRecord Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new MedicalRecord(name, id, options);
        }
    }

    public sealed class MedicalRecordArgs : Pulumi.ResourceArgs
    {
        [Input("date")]
        public Input<string>? Date { get; set; }

        [Input("healthcareProfessional")]
        public Input<string>? HealthcareProfessional { get; set; }

        [Input("location")]
        public Input<string>? Location { get; set; }

        [Input("medication")]
        public Input<Pulumi.MedicalRecord.Section.Inputs.Medication>? Medication { get; set; }

        [Input("notes")]
        public Input<string>? Notes { get; set; }

        [Input("patient")]
        public Input<string>? Patient { get; set; }

        [Input("reasonForVisit")]
        public Input<string>? ReasonForVisit { get; set; }

        public MedicalRecordArgs()
        {
        }
    }
}
