
export const ItemType = {
"APICredentialItem": "one-password-native-unofficial:index:APICredentialItem",
"BankAccountItem": "one-password-native-unofficial:index:BankAccountItem",
"CreditCardItem": "one-password-native-unofficial:index:CreditCardItem",
"CryptoWalletItem": "one-password-native-unofficial:index:CryptoWalletItem",
"DatabaseItem": "one-password-native-unofficial:index:DatabaseItem",
"DocumentItem": "one-password-native-unofficial:index:DocumentItem",
"DriverLicenseItem": "one-password-native-unofficial:index:DriverLicenseItem",
"EmailAccountItem": "one-password-native-unofficial:index:EmailAccountItem",
"IdentityItem": "one-password-native-unofficial:index:IdentityItem",
"Item": "one-password-native-unofficial:index:Item",
"LoginItem": "one-password-native-unofficial:index:LoginItem",
"MedicalRecordItem": "one-password-native-unofficial:index:MedicalRecordItem",
"MembershipItem": "one-password-native-unofficial:index:MembershipItem",
"OutdoorLicenseItem": "one-password-native-unofficial:index:OutdoorLicenseItem",
"PassportItem": "one-password-native-unofficial:index:PassportItem",
"PasswordItem": "one-password-native-unofficial:index:PasswordItem",
"RewardProgramItem": "one-password-native-unofficial:index:RewardProgramItem",
"SSHKeyItem": "one-password-native-unofficial:index:SSHKeyItem",
"SecureNoteItem": "one-password-native-unofficial:index:SecureNoteItem",
"ServerItem": "one-password-native-unofficial:index:ServerItem",
"SocialSecurityNumberItem": "one-password-native-unofficial:index:SocialSecurityNumberItem",
"SoftwareLicenseItem": "one-password-native-unofficial:index:SoftwareLicenseItem",
"WirelessRouterItem": "one-password-native-unofficial:index:WirelessRouterItem",
"GetItem": "one-password-native-unofficial:index:GetItem",
"GetVault": "one-password-native-unofficial:index:GetVault",
"GetSecretReference": "one-password-native-unofficial:index:GetSecretReference",
"GetAttachment": "one-password-native-unofficial:index:GetAttachment",
"GetAPICredential": "one-password-native-unofficial:index:GetAPICredential",
"GetBankAccount": "one-password-native-unofficial:index:GetBankAccount",
"GetCreditCard": "one-password-native-unofficial:index:GetCreditCard",
"GetCryptoWallet": "one-password-native-unofficial:index:GetCryptoWallet",
"GetDatabase": "one-password-native-unofficial:index:GetDatabase",
"GetDocument": "one-password-native-unofficial:index:GetDocument",
"GetDriverLicense": "one-password-native-unofficial:index:GetDriverLicense",
"GetEmailAccount": "one-password-native-unofficial:index:GetEmailAccount",
"GetIdentity": "one-password-native-unofficial:index:GetIdentity",
"GetLogin": "one-password-native-unofficial:index:GetLogin",
"GetMedicalRecord": "one-password-native-unofficial:index:GetMedicalRecord",
"GetMembership": "one-password-native-unofficial:index:GetMembership",
"GetOutdoorLicense": "one-password-native-unofficial:index:GetOutdoorLicense",
"GetPassport": "one-password-native-unofficial:index:GetPassport",
"GetPassword": "one-password-native-unofficial:index:GetPassword",
"GetRewardProgram": "one-password-native-unofficial:index:GetRewardProgram",
"GetSSHKey": "one-password-native-unofficial:index:GetSSHKey",
"GetSecureNote": "one-password-native-unofficial:index:GetSecureNote",
"GetServer": "one-password-native-unofficial:index:GetServer",
"GetSocialSecurityNumber": "one-password-native-unofficial:index:GetSocialSecurityNumber",
"GetSoftwareLicense": "one-password-native-unofficial:index:GetSoftwareLicense",
"GetWirelessRouter": "one-password-native-unofficial:index:GetWirelessRouter"
} as const;
export const ItemTypeNames = {
"one-password-native-unofficial:index:APICredentialItem": "API Credential",
"one-password-native-unofficial:index:BankAccountItem": "Bank Account",
"one-password-native-unofficial:index:CreditCardItem": "Credit Card",
"one-password-native-unofficial:index:CryptoWalletItem": "Crypto Wallet",
"one-password-native-unofficial:index:DatabaseItem": "Database",
"one-password-native-unofficial:index:DocumentItem": "Document",
"one-password-native-unofficial:index:DriverLicenseItem": "Driver License",
"one-password-native-unofficial:index:EmailAccountItem": "Email Account",
"one-password-native-unofficial:index:IdentityItem": "Identity",
"one-password-native-unofficial:index:Item": "Item",
"one-password-native-unofficial:index:LoginItem": "Login",
"one-password-native-unofficial:index:MedicalRecordItem": "Medical Record",
"one-password-native-unofficial:index:MembershipItem": "Membership",
"one-password-native-unofficial:index:OutdoorLicenseItem": "Outdoor License",
"one-password-native-unofficial:index:PassportItem": "Passport",
"one-password-native-unofficial:index:PasswordItem": "Password",
"one-password-native-unofficial:index:RewardProgramItem": "Reward Program",
"one-password-native-unofficial:index:SSHKeyItem": "SSH Key",
"one-password-native-unofficial:index:SecureNoteItem": "Secure Note",
"one-password-native-unofficial:index:ServerItem": "Server",
"one-password-native-unofficial:index:SocialSecurityNumberItem": "Social Security Number",
"one-password-native-unofficial:index:SoftwareLicenseItem": "Software License",
"one-password-native-unofficial:index:WirelessRouterItem": "Wireless Router",
"one-password-native-unofficial:index:GetAPICredential": "API Credential",
"one-password-native-unofficial:index:GetBankAccount": "Bank Account",
"one-password-native-unofficial:index:GetCreditCard": "Credit Card",
"one-password-native-unofficial:index:GetCryptoWallet": "Crypto Wallet",
"one-password-native-unofficial:index:GetDatabase": "Database",
"one-password-native-unofficial:index:GetDocument": "Document",
"one-password-native-unofficial:index:GetDriverLicense": "Driver License",
"one-password-native-unofficial:index:GetEmailAccount": "Email Account",
"one-password-native-unofficial:index:GetIdentity": "Identity",
"one-password-native-unofficial:index:GetItem": "Item",
"one-password-native-unofficial:index:GetLogin": "Login",
"one-password-native-unofficial:index:GetMedicalRecord": "Medical Record",
"one-password-native-unofficial:index:GetMembership": "Membership",
"one-password-native-unofficial:index:GetOutdoorLicense": "Outdoor License",
"one-password-native-unofficial:index:GetPassport": "Passport",
"one-password-native-unofficial:index:GetPassword": "Password",
"one-password-native-unofficial:index:GetRewardProgram": "Reward Program",
"one-password-native-unofficial:index:GetSSHKey": "SSH Key",
"one-password-native-unofficial:index:GetSecureNote": "Secure Note",
"one-password-native-unofficial:index:GetServer": "Server",
"one-password-native-unofficial:index:GetSocialSecurityNumber": "Social Security Number",
"one-password-native-unofficial:index:GetSoftwareLicense": "Software License",
"one-password-native-unofficial:index:GetWirelessRouter": "Wireless Router",
"one-password-native-unofficial:index:GetVault": "Vault",
"one-password-native-unofficial:index:GetSecretReference": "Secret Reference",
"one-password-native-unofficial:index:GetAttachment": "Attachment"
} as const;
export const ResourceTypes = ["one-password-native-unofficial:index:APICredentialItem", "one-password-native-unofficial:index:BankAccountItem", "one-password-native-unofficial:index:CreditCardItem", "one-password-native-unofficial:index:CryptoWalletItem", "one-password-native-unofficial:index:DatabaseItem", "one-password-native-unofficial:index:DocumentItem", "one-password-native-unofficial:index:DriverLicenseItem", "one-password-native-unofficial:index:EmailAccountItem", "one-password-native-unofficial:index:IdentityItem", "one-password-native-unofficial:index:Item", "one-password-native-unofficial:index:LoginItem", "one-password-native-unofficial:index:MedicalRecordItem", "one-password-native-unofficial:index:MembershipItem", "one-password-native-unofficial:index:OutdoorLicenseItem", "one-password-native-unofficial:index:PassportItem", "one-password-native-unofficial:index:PasswordItem", "one-password-native-unofficial:index:RewardProgramItem", "one-password-native-unofficial:index:SSHKeyItem", "one-password-native-unofficial:index:SecureNoteItem", "one-password-native-unofficial:index:ServerItem", "one-password-native-unofficial:index:SocialSecurityNumberItem", "one-password-native-unofficial:index:SoftwareLicenseItem", "one-password-native-unofficial:index:WirelessRouterItem"] as const;
export const FunctionTypes = ["one-password-native-unofficial:index:GetItem", "one-password-native-unofficial:index:GetVault", "one-password-native-unofficial:index:GetSecretReference", "one-password-native-unofficial:index:GetAttachment", "one-password-native-unofficial:index:GetAPICredential", "one-password-native-unofficial:index:GetBankAccount", "one-password-native-unofficial:index:GetCreditCard", "one-password-native-unofficial:index:GetCryptoWallet", "one-password-native-unofficial:index:GetDatabase", "one-password-native-unofficial:index:GetDocument", "one-password-native-unofficial:index:GetDriverLicense", "one-password-native-unofficial:index:GetEmailAccount", "one-password-native-unofficial:index:GetIdentity", "one-password-native-unofficial:index:GetLogin", "one-password-native-unofficial:index:GetMedicalRecord", "one-password-native-unofficial:index:GetMembership", "one-password-native-unofficial:index:GetOutdoorLicense", "one-password-native-unofficial:index:GetPassport", "one-password-native-unofficial:index:GetPassword", "one-password-native-unofficial:index:GetRewardProgram", "one-password-native-unofficial:index:GetSSHKey", "one-password-native-unofficial:index:GetSecureNote", "one-password-native-unofficial:index:GetServer", "one-password-native-unofficial:index:GetSocialSecurityNumber", "one-password-native-unofficial:index:GetSoftwareLicense", "one-password-native-unofficial:index:GetWirelessRouter"] as const;
export const PropertyPaths: Record<string, [field: string, section?: string][]> = {
    "one-password-native-unofficial:index:APICredentialItem": [["notes"],["username"],["credential"],["type"],["filename"],["validFrom"],["expires"],["hostname"]],
"one-password-native-unofficial:index:BankAccountItem": [["notes"],["bankName"],["nameOnAccount"],["type"],["routingNumber"],["accountNumber"],["swift"],["iban"],["pin"],["phone","branchInformation"],["address","branchInformation"]],
"one-password-native-unofficial:index:CreditCardItem": [["notes"],["cardholderName"],["type"],["number"],["verificationNumber"],["expiryDate"],["validFrom"],["issuingBank","contactInformation"],["phoneLocal","contactInformation"],["phoneTollFree","contactInformation"],["phoneIntl","contactInformation"],["website","contactInformation"],["pin","additionalDetails"],["creditLimit","additionalDetails"],["cashWithdrawalLimit","additionalDetails"],["interestRate","additionalDetails"],["issueNumber","additionalDetails"]],
"one-password-native-unofficial:index:CryptoWalletItem": [["notes"],["recoveryPhrase"],["password"],["walletAddress","wallet"]],
"one-password-native-unofficial:index:DatabaseItem": [["notes"],["type"],["server"],["port"],["database"],["username"],["password"],["sid"],["alias"],["connectionOptions"]],
"one-password-native-unofficial:index:DocumentItem": [["notes"]],
"one-password-native-unofficial:index:DriverLicenseItem": [["notes"],["fullName"],["address"],["dateOfBirth"],["gender"],["height"],["number"],["licenseClass"],["conditionsRestrictions"],["state"],["country"],["expiryDate"]],
"one-password-native-unofficial:index:EmailAccountItem": [["notes"],["type"],["username"],["server"],["portNumber"],["password"],["security"],["authMethod"],["smtpServer","smtp"],["portNumber","smtp"],["username","smtp"],["password","smtp"],["security","smtp"],["authMethod","smtp"],["provider","contactInformation"],["providersWebsite","contactInformation"],["phoneLocal","contactInformation"],["phoneTollFree","contactInformation"]],
"one-password-native-unofficial:index:IdentityItem": [["notes"],["firstName","identification"],["initial","identification"],["lastName","identification"],["gender","identification"],["birthDate","identification"],["occupation","identification"],["company","identification"],["department","identification"],["jobTitle","identification"],["address","address"],["defaultPhone","address"],["home","address"],["cell","address"],["business","address"],["username","internetDetails"],["reminderQuestion","internetDetails"],["reminderAnswer","internetDetails"],["email","internetDetails"],["website","internetDetails"],["icq","internetDetails"],["skype","internetDetails"],["aolAim","internetDetails"],["yahoo","internetDetails"],["msn","internetDetails"],["forumSignature","internetDetails"]],
"one-password-native-unofficial:index:Item": [["notes"]],
"one-password-native-unofficial:index:LoginItem": [["username"],["password"],["notes"]],
"one-password-native-unofficial:index:MedicalRecordItem": [["notes"],["date"],["location"],["healthcareProfessional"],["patient"],["reasonForVisit"],["medication","medication"],["dosage","medication"],["medicationNotes","medication"]],
"one-password-native-unofficial:index:MembershipItem": [["notes"],["group"],["website"],["telephone"],["memberName"],["memberSince"],["expiryDate"],["memberId"],["pin"]],
"one-password-native-unofficial:index:OutdoorLicenseItem": [["notes"],["fullName"],["validFrom"],["expires"],["approvedWildlife"],["maximumQuota"],["state"],["country"]],
"one-password-native-unofficial:index:PassportItem": [["notes"],["type"],["issuingCountry"],["number"],["fullName"],["gender"],["nationality"],["issuingAuthority"],["dateOfBirth"],["placeOfBirth"],["issuedOn"],["expiryDate"]],
"one-password-native-unofficial:index:PasswordItem": [["password"],["notes"]],
"one-password-native-unofficial:index:RewardProgramItem": [["notes"],["companyName"],["memberName"],["memberId"],["pin"],["memberIdAdditional","moreInformation"],["memberSince","moreInformation"],["customerServicePhone","moreInformation"],["phoneForReservations","moreInformation"],["website","moreInformation"]],
"one-password-native-unofficial:index:SSHKeyItem": [["notes"],["privateKey"]],
"one-password-native-unofficial:index:SecureNoteItem": [["notes"]],
"one-password-native-unofficial:index:ServerItem": [["notes"],["url"],["username"],["password"],["adminConsoleUrl","adminConsole"],["adminConsoleUsername","adminConsole"],["consolePassword","adminConsole"],["name","hostingProvider"],["website","hostingProvider"],["supportUrl","hostingProvider"],["supportPhone","hostingProvider"]],
"one-password-native-unofficial:index:SocialSecurityNumberItem": [["notes"],["name"],["number"]],
"one-password-native-unofficial:index:SoftwareLicenseItem": [["notes"],["version"],["licenseKey"],["licensedTo","customer"],["registeredEmail","customer"],["company","customer"],["downloadPage","publisher"],["publisher","publisher"],["website","publisher"],["retailPrice","publisher"],["supportEmail","publisher"],["purchaseDate","order"],["orderNumber","order"],["orderTotal","order"]],
"one-password-native-unofficial:index:WirelessRouterItem": [["notes"],["baseStationName"],["baseStationPassword"],["serverIpAddress"],["airPortId"],["networkName"],["wirelessSecurity"],["wirelessNetworkPassword"],["attachedStoragePassword"]],
"one-password-native-unofficial:index:GetAPICredential": [["notes"],["username"],["credential"],["type"],["filename"],["validFrom"],["expires"],["hostname"]],
"one-password-native-unofficial:index:GetBankAccount": [["notes"],["bankName"],["nameOnAccount"],["type"],["routingNumber"],["accountNumber"],["swift"],["iban"],["pin"],["phone","branchInformation"],["address","branchInformation"]],
"one-password-native-unofficial:index:GetCreditCard": [["notes"],["cardholderName"],["type"],["number"],["verificationNumber"],["expiryDate"],["validFrom"],["issuingBank","contactInformation"],["phoneLocal","contactInformation"],["phoneTollFree","contactInformation"],["phoneIntl","contactInformation"],["website","contactInformation"],["pin","additionalDetails"],["creditLimit","additionalDetails"],["cashWithdrawalLimit","additionalDetails"],["interestRate","additionalDetails"],["issueNumber","additionalDetails"]],
"one-password-native-unofficial:index:GetCryptoWallet": [["notes"],["recoveryPhrase"],["password"],["walletAddress","wallet"]],
"one-password-native-unofficial:index:GetDatabase": [["notes"],["type"],["server"],["port"],["database"],["username"],["password"],["sid"],["alias"],["connectionOptions"]],
"one-password-native-unofficial:index:GetDocument": [["notes"]],
"one-password-native-unofficial:index:GetDriverLicense": [["notes"],["fullName"],["address"],["dateOfBirth"],["gender"],["height"],["number"],["licenseClass"],["conditionsRestrictions"],["state"],["country"],["expiryDate"]],
"one-password-native-unofficial:index:GetEmailAccount": [["notes"],["type"],["username"],["server"],["portNumber"],["password"],["security"],["authMethod"],["smtpServer","smtp"],["portNumber","smtp"],["username","smtp"],["password","smtp"],["security","smtp"],["authMethod","smtp"],["provider","contactInformation"],["providersWebsite","contactInformation"],["phoneLocal","contactInformation"],["phoneTollFree","contactInformation"]],
"one-password-native-unofficial:index:GetIdentity": [["notes"],["firstName","identification"],["initial","identification"],["lastName","identification"],["gender","identification"],["birthDate","identification"],["occupation","identification"],["company","identification"],["department","identification"],["jobTitle","identification"],["address","address"],["defaultPhone","address"],["home","address"],["cell","address"],["business","address"],["username","internetDetails"],["reminderQuestion","internetDetails"],["reminderAnswer","internetDetails"],["email","internetDetails"],["website","internetDetails"],["icq","internetDetails"],["skype","internetDetails"],["aolAim","internetDetails"],["yahoo","internetDetails"],["msn","internetDetails"],["forumSignature","internetDetails"]],
"one-password-native-unofficial:index:GetItem": [["notes"]],
"one-password-native-unofficial:index:GetLogin": [["username"],["password"],["notes"]],
"one-password-native-unofficial:index:GetMedicalRecord": [["notes"],["date"],["location"],["healthcareProfessional"],["patient"],["reasonForVisit"],["medication","medication"],["dosage","medication"],["medicationNotes","medication"]],
"one-password-native-unofficial:index:GetMembership": [["notes"],["group"],["website"],["telephone"],["memberName"],["memberSince"],["expiryDate"],["memberId"],["pin"]],
"one-password-native-unofficial:index:GetOutdoorLicense": [["notes"],["fullName"],["validFrom"],["expires"],["approvedWildlife"],["maximumQuota"],["state"],["country"]],
"one-password-native-unofficial:index:GetPassport": [["notes"],["type"],["issuingCountry"],["number"],["fullName"],["gender"],["nationality"],["issuingAuthority"],["dateOfBirth"],["placeOfBirth"],["issuedOn"],["expiryDate"]],
"one-password-native-unofficial:index:GetPassword": [["password"],["notes"]],
"one-password-native-unofficial:index:GetRewardProgram": [["notes"],["companyName"],["memberName"],["memberId"],["pin"],["memberIdAdditional","moreInformation"],["memberSince","moreInformation"],["customerServicePhone","moreInformation"],["phoneForReservations","moreInformation"],["website","moreInformation"]],
"one-password-native-unofficial:index:GetSSHKey": [["notes"],["privateKey"]],
"one-password-native-unofficial:index:GetSecureNote": [["notes"]],
"one-password-native-unofficial:index:GetServer": [["notes"],["url"],["username"],["password"],["adminConsoleUrl","adminConsole"],["adminConsoleUsername","adminConsole"],["consolePassword","adminConsole"],["name","hostingProvider"],["website","hostingProvider"],["supportUrl","hostingProvider"],["supportPhone","hostingProvider"]],
"one-password-native-unofficial:index:GetSocialSecurityNumber": [["notes"],["name"],["number"]],
"one-password-native-unofficial:index:GetSoftwareLicense": [["notes"],["version"],["licenseKey"],["licensedTo","customer"],["registeredEmail","customer"],["company","customer"],["downloadPage","publisher"],["publisher","publisher"],["website","publisher"],["retailPrice","publisher"],["supportEmail","publisher"],["purchaseDate","order"],["orderNumber","order"],["orderTotal","order"]],
"one-password-native-unofficial:index:GetWirelessRouter": [["notes"],["baseStationName"],["baseStationPassword"],["serverIpAddress"],["airPortId"],["networkName"],["wirelessSecurity"],["wirelessNetworkPassword"],["attachedStoragePassword"]]
}
