
export const ItemType = {
"MembershipItem": "onepassword:index:MembershipItem",
"PassportItem": "onepassword:index:PassportItem",
"PasswordItem": "onepassword:index:PasswordItem",
"ServerItem": "onepassword:index:ServerItem",
"EmailAccountItem": "onepassword:index:EmailAccountItem",
"IdentityItem": "onepassword:index:IdentityItem",
"LoginItem": "onepassword:index:LoginItem",
"RewardProgramItem": "onepassword:index:RewardProgramItem",
"WirelessRouterItem": "onepassword:index:WirelessRouterItem",
"APICredentialItem": "onepassword:index:APICredentialItem",
"BankAccountItem": "onepassword:index:BankAccountItem",
"CreditCardItem": "onepassword:index:CreditCardItem",
"DatabaseItem": "onepassword:index:DatabaseItem",
"DriverLicenseItem": "onepassword:index:DriverLicenseItem",
"MedicalRecordItem": "onepassword:index:MedicalRecordItem",
"OutdoorLicenseItem": "onepassword:index:OutdoorLicenseItem",
"SecureNoteItem": "onepassword:index:SecureNoteItem",
"SoftwareLicenseItem": "onepassword:index:SoftwareLicenseItem",
"CryptoWalletItem": "onepassword:index:CryptoWalletItem",
"DocumentItem": "onepassword:index:DocumentItem",
"SocialSecurityNumberItem": "onepassword:index:SocialSecurityNumberItem",
"SSHKeyItem": "onepassword:index:SSHKeyItem",
"Item": "onepassword:index:Item",
"GetItem": "onepassword:index:GetItem",
"GetVault": "onepassword:index:GetVault",
"GetSecretReference": "onepassword:index:GetSecretReference",
"GetAttachment": "onepassword:index:GetAttachment",
"GetPassword": "onepassword:index:GetPassword",
"PasswordItem/attachment": "onepassword:index:PasswordItem/attachment",
"GetWirelessRouter": "onepassword:index:GetWirelessRouter",
"WirelessRouterItem/attachment": "onepassword:index:WirelessRouterItem/attachment",
"GetSSHKey": "onepassword:index:GetSSHKey",
"SSHKeyItem/attachment": "onepassword:index:SSHKeyItem/attachment",
"GetDocument": "onepassword:index:GetDocument",
"DocumentItem/attachment": "onepassword:index:DocumentItem/attachment",
"GetMembership": "onepassword:index:GetMembership",
"MembershipItem/attachment": "onepassword:index:MembershipItem/attachment",
"GetIdentity": "onepassword:index:GetIdentity",
"IdentityItem/attachment": "onepassword:index:IdentityItem/attachment",
"GetPassport": "onepassword:index:GetPassport",
"PassportItem/attachment": "onepassword:index:PassportItem/attachment",
"GetCreditCard": "onepassword:index:GetCreditCard",
"CreditCardItem/attachment": "onepassword:index:CreditCardItem/attachment",
"GetCryptoWallet": "onepassword:index:GetCryptoWallet",
"CryptoWalletItem/attachment": "onepassword:index:CryptoWalletItem/attachment",
"GetDriverLicense": "onepassword:index:GetDriverLicense",
"DriverLicenseItem/attachment": "onepassword:index:DriverLicenseItem/attachment",
"GetOutdoorLicense": "onepassword:index:GetOutdoorLicense",
"OutdoorLicenseItem/attachment": "onepassword:index:OutdoorLicenseItem/attachment",
"GetSocialSecurityNumber": "onepassword:index:GetSocialSecurityNumber",
"SocialSecurityNumberItem/attachment": "onepassword:index:SocialSecurityNumberItem/attachment",
"GetAPICredential": "onepassword:index:GetAPICredential",
"APICredentialItem/attachment": "onepassword:index:APICredentialItem/attachment",
"GetDatabase": "onepassword:index:GetDatabase",
"DatabaseItem/attachment": "onepassword:index:DatabaseItem/attachment",
"GetLogin": "onepassword:index:GetLogin",
"LoginItem/attachment": "onepassword:index:LoginItem/attachment",
"GetMedicalRecord": "onepassword:index:GetMedicalRecord",
"MedicalRecordItem/attachment": "onepassword:index:MedicalRecordItem/attachment",
"GetRewardProgram": "onepassword:index:GetRewardProgram",
"RewardProgramItem/attachment": "onepassword:index:RewardProgramItem/attachment",
"GetSecureNote": "onepassword:index:GetSecureNote",
"SecureNoteItem/attachment": "onepassword:index:SecureNoteItem/attachment",
"GetServer": "onepassword:index:GetServer",
"ServerItem/attachment": "onepassword:index:ServerItem/attachment",
"GetSoftwareLicense": "onepassword:index:GetSoftwareLicense",
"SoftwareLicenseItem/attachment": "onepassword:index:SoftwareLicenseItem/attachment",
"GetBankAccount": "onepassword:index:GetBankAccount",
"BankAccountItem/attachment": "onepassword:index:BankAccountItem/attachment",
"GetEmailAccount": "onepassword:index:GetEmailAccount",
"EmailAccountItem/attachment": "onepassword:index:EmailAccountItem/attachment",
"Item/attachment": "onepassword:index:Item/attachment"
} as const;
export const ItemTypeNames = {
"onepassword:index:PasswordItem": "Password",
"onepassword:index:WirelessRouterItem": "Wireless Router",
"onepassword:index:SSHKeyItem": "SSH Key",
"onepassword:index:DocumentItem": "Document",
"onepassword:index:MembershipItem": "Membership",
"onepassword:index:IdentityItem": "Identity",
"onepassword:index:PassportItem": "Passport",
"onepassword:index:CreditCardItem": "Credit Card",
"onepassword:index:CryptoWalletItem": "Crypto Wallet",
"onepassword:index:DriverLicenseItem": "Driver License",
"onepassword:index:OutdoorLicenseItem": "Outdoor License",
"onepassword:index:SocialSecurityNumberItem": "Social Security Number",
"onepassword:index:APICredentialItem": "API Credential",
"onepassword:index:DatabaseItem": "Database",
"onepassword:index:LoginItem": "Login",
"onepassword:index:MedicalRecordItem": "Medical Record",
"onepassword:index:RewardProgramItem": "Reward Program",
"onepassword:index:SecureNoteItem": "Secure Note",
"onepassword:index:ServerItem": "Server",
"onepassword:index:SoftwareLicenseItem": "Software License",
"onepassword:index:BankAccountItem": "Bank Account",
"onepassword:index:EmailAccountItem": "Email Account",
"onepassword:index:Item": "Item",
"onepassword:index:GetPassword": "Password",
"onepassword:index:GetWirelessRouter": "Wireless Router",
"onepassword:index:GetSSHKey": "SSH Key",
"onepassword:index:GetDocument": "Document",
"onepassword:index:GetMembership": "Membership",
"onepassword:index:GetIdentity": "Identity",
"onepassword:index:GetPassport": "Passport",
"onepassword:index:GetCreditCard": "Credit Card",
"onepassword:index:GetCryptoWallet": "Crypto Wallet",
"onepassword:index:GetDriverLicense": "Driver License",
"onepassword:index:GetOutdoorLicense": "Outdoor License",
"onepassword:index:GetSocialSecurityNumber": "Social Security Number",
"onepassword:index:GetAPICredential": "API Credential",
"onepassword:index:GetDatabase": "Database",
"onepassword:index:GetLogin": "Login",
"onepassword:index:GetMedicalRecord": "Medical Record",
"onepassword:index:GetRewardProgram": "Reward Program",
"onepassword:index:GetSecureNote": "Secure Note",
"onepassword:index:GetServer": "Server",
"onepassword:index:GetSoftwareLicense": "Software License",
"onepassword:index:GetBankAccount": "Bank Account",
"onepassword:index:GetEmailAccount": "Email Account",
"onepassword:index:GetItem": "Item",
"onepassword:index:GetVault": "Vault",
"onepassword:index:GetSecretReference": "Secret Reference",
"onepassword:index:GetAttachment": "Attachment"
} as const;
export const ResourceTypes = ["onepassword:index:MembershipItem", "onepassword:index:PassportItem", "onepassword:index:PasswordItem", "onepassword:index:ServerItem", "onepassword:index:EmailAccountItem", "onepassword:index:IdentityItem", "onepassword:index:LoginItem", "onepassword:index:RewardProgramItem", "onepassword:index:WirelessRouterItem", "onepassword:index:APICredentialItem", "onepassword:index:BankAccountItem", "onepassword:index:CreditCardItem", "onepassword:index:DatabaseItem", "onepassword:index:DriverLicenseItem", "onepassword:index:MedicalRecordItem", "onepassword:index:OutdoorLicenseItem", "onepassword:index:SecureNoteItem", "onepassword:index:SoftwareLicenseItem", "onepassword:index:CryptoWalletItem", "onepassword:index:DocumentItem", "onepassword:index:SocialSecurityNumberItem", "onepassword:index:SSHKeyItem", "onepassword:index:Item"] as const;
export const FunctionTypes = ["onepassword:index:GetItem", "onepassword:index:GetVault", "onepassword:index:GetSecretReference", "onepassword:index:GetAttachment", "onepassword:index:GetPassword", "onepassword:index:PasswordItem/attachment", "onepassword:index:GetWirelessRouter", "onepassword:index:WirelessRouterItem/attachment", "onepassword:index:GetSSHKey", "onepassword:index:SSHKeyItem/attachment", "onepassword:index:GetDocument", "onepassword:index:DocumentItem/attachment", "onepassword:index:GetMembership", "onepassword:index:MembershipItem/attachment", "onepassword:index:GetIdentity", "onepassword:index:IdentityItem/attachment", "onepassword:index:GetPassport", "onepassword:index:PassportItem/attachment", "onepassword:index:GetCreditCard", "onepassword:index:CreditCardItem/attachment", "onepassword:index:GetCryptoWallet", "onepassword:index:CryptoWalletItem/attachment", "onepassword:index:GetDriverLicense", "onepassword:index:DriverLicenseItem/attachment", "onepassword:index:GetOutdoorLicense", "onepassword:index:OutdoorLicenseItem/attachment", "onepassword:index:GetSocialSecurityNumber", "onepassword:index:SocialSecurityNumberItem/attachment", "onepassword:index:GetAPICredential", "onepassword:index:APICredentialItem/attachment", "onepassword:index:GetDatabase", "onepassword:index:DatabaseItem/attachment", "onepassword:index:GetLogin", "onepassword:index:LoginItem/attachment", "onepassword:index:GetMedicalRecord", "onepassword:index:MedicalRecordItem/attachment", "onepassword:index:GetRewardProgram", "onepassword:index:RewardProgramItem/attachment", "onepassword:index:GetSecureNote", "onepassword:index:SecureNoteItem/attachment", "onepassword:index:GetServer", "onepassword:index:ServerItem/attachment", "onepassword:index:GetSoftwareLicense", "onepassword:index:SoftwareLicenseItem/attachment", "onepassword:index:GetBankAccount", "onepassword:index:BankAccountItem/attachment", "onepassword:index:GetEmailAccount", "onepassword:index:EmailAccountItem/attachment", "onepassword:index:Item/attachment"] as const;
export const PropertyPaths: Record<string, [field: string, section?: string][]> = {
    "onepassword:index:PasswordItem": [["password"],["notes"]],
"onepassword:index:WirelessRouterItem": [["notes"],["baseStationName"],["baseStationPassword"],["serverIpAddress"],["airPortId"],["networkName"],["wirelessSecurity"],["wirelessNetworkPassword"],["attachedStoragePassword"]],
"onepassword:index:SSHKeyItem": [["notes"],["privateKey"]],
"onepassword:index:DocumentItem": [["notes"]],
"onepassword:index:MembershipItem": [["notes"],["group"],["website"],["telephone"],["memberName"],["memberSince"],["expiryDate"],["memberId"],["pin"]],
"onepassword:index:IdentityItem": [["notes"],["firstName","identification"],["initial","identification"],["lastName","identification"],["gender","identification"],["birthDate","identification"],["occupation","identification"],["company","identification"],["department","identification"],["jobTitle","identification"],["address","address"],["defaultPhone","address"],["home","address"],["cell","address"],["business","address"],["username","internetDetails"],["reminderQuestion","internetDetails"],["reminderAnswer","internetDetails"],["email","internetDetails"],["website","internetDetails"],["icq","internetDetails"],["skype","internetDetails"],["aolAim","internetDetails"],["yahoo","internetDetails"],["msn","internetDetails"],["forumSignature","internetDetails"]],
"onepassword:index:PassportItem": [["notes"],["type"],["issuingCountry"],["number"],["fullName"],["gender"],["nationality"],["issuingAuthority"],["dateOfBirth"],["placeOfBirth"],["issuedOn"],["expiryDate"]],
"onepassword:index:CreditCardItem": [["notes"],["cardholderName"],["type"],["number"],["verificationNumber"],["expiryDate"],["validFrom"],["issuingBank","contactInformation"],["phoneLocal","contactInformation"],["phoneTollFree","contactInformation"],["phoneIntl","contactInformation"],["website","contactInformation"],["pin","additionalDetails"],["creditLimit","additionalDetails"],["cashWithdrawalLimit","additionalDetails"],["interestRate","additionalDetails"],["issueNumber","additionalDetails"]],
"onepassword:index:CryptoWalletItem": [["notes"],["recoveryPhrase"],["password"],["walletAddress","wallet"]],
"onepassword:index:DriverLicenseItem": [["notes"],["fullName"],["address"],["dateOfBirth"],["gender"],["height"],["number"],["licenseClass"],["conditionsRestrictions"],["state"],["country"],["expiryDate"]],
"onepassword:index:OutdoorLicenseItem": [["notes"],["fullName"],["validFrom"],["expires"],["approvedWildlife"],["maximumQuota"],["state"],["country"]],
"onepassword:index:SocialSecurityNumberItem": [["notes"],["name"],["number"]],
"onepassword:index:APICredentialItem": [["notes"],["username"],["credential"],["type"],["filename"],["validFrom"],["expires"],["hostname"]],
"onepassword:index:DatabaseItem": [["notes"],["type"],["server"],["port"],["database"],["username"],["password"],["sid"],["alias"],["connectionOptions"]],
"onepassword:index:LoginItem": [["username"],["password"],["notes"]],
"onepassword:index:MedicalRecordItem": [["notes"],["date"],["location"],["healthcareProfessional"],["patient"],["reasonForVisit"],["medication","medication"],["dosage","medication"],["medicationNotes","medication"]],
"onepassword:index:RewardProgramItem": [["notes"],["companyName"],["memberName"],["memberId"],["pin"],["memberIdAdditional","moreInformation"],["memberSince","moreInformation"],["customerServicePhone","moreInformation"],["phoneForReservations","moreInformation"],["website","moreInformation"]],
"onepassword:index:SecureNoteItem": [["notes"]],
"onepassword:index:ServerItem": [["notes"],["url"],["username"],["password"],["adminConsoleUrl","adminConsole"],["adminConsoleUsername","adminConsole"],["consolePassword","adminConsole"],["name","hostingProvider"],["website","hostingProvider"],["supportUrl","hostingProvider"],["supportPhone","hostingProvider"]],
"onepassword:index:SoftwareLicenseItem": [["notes"],["version"],["licenseKey"],["licensedTo","customer"],["registeredEmail","customer"],["company","customer"],["downloadPage","publisher"],["publisher","publisher"],["website","publisher"],["retailPrice","publisher"],["supportEmail","publisher"],["purchaseDate","order"],["orderNumber","order"],["orderTotal","order"]],
"onepassword:index:BankAccountItem": [["notes"],["bankName"],["nameOnAccount"],["type"],["routingNumber"],["accountNumber"],["swift"],["iban"],["pin"],["phone","branchInformation"],["address","branchInformation"]],
"onepassword:index:EmailAccountItem": [["notes"],["type"],["username"],["server"],["portNumber"],["password"],["security"],["authMethod"],["smtpServer","smtp"],["portNumber","smtp"],["username","smtp"],["password","smtp"],["security","smtp"],["authMethod","smtp"],["provider","contactInformation"],["providersWebsite","contactInformation"],["phoneLocal","contactInformation"],["phoneTollFree","contactInformation"]],
"onepassword:index:GetPassword": [["password"],["notes"]],
"onepassword:index:GetWirelessRouter": [["notes"],["baseStationName"],["baseStationPassword"],["serverIpAddress"],["airPortId"],["networkName"],["wirelessSecurity"],["wirelessNetworkPassword"],["attachedStoragePassword"]],
"onepassword:index:GetSSHKey": [["notes"],["privateKey"]],
"onepassword:index:GetDocument": [["notes"]],
"onepassword:index:GetMembership": [["notes"],["group"],["website"],["telephone"],["memberName"],["memberSince"],["expiryDate"],["memberId"],["pin"]],
"onepassword:index:GetIdentity": [["notes"],["firstName","identification"],["initial","identification"],["lastName","identification"],["gender","identification"],["birthDate","identification"],["occupation","identification"],["company","identification"],["department","identification"],["jobTitle","identification"],["address","address"],["defaultPhone","address"],["home","address"],["cell","address"],["business","address"],["username","internetDetails"],["reminderQuestion","internetDetails"],["reminderAnswer","internetDetails"],["email","internetDetails"],["website","internetDetails"],["icq","internetDetails"],["skype","internetDetails"],["aolAim","internetDetails"],["yahoo","internetDetails"],["msn","internetDetails"],["forumSignature","internetDetails"]],
"onepassword:index:GetPassport": [["notes"],["type"],["issuingCountry"],["number"],["fullName"],["gender"],["nationality"],["issuingAuthority"],["dateOfBirth"],["placeOfBirth"],["issuedOn"],["expiryDate"]],
"onepassword:index:GetCreditCard": [["notes"],["cardholderName"],["type"],["number"],["verificationNumber"],["expiryDate"],["validFrom"],["issuingBank","contactInformation"],["phoneLocal","contactInformation"],["phoneTollFree","contactInformation"],["phoneIntl","contactInformation"],["website","contactInformation"],["pin","additionalDetails"],["creditLimit","additionalDetails"],["cashWithdrawalLimit","additionalDetails"],["interestRate","additionalDetails"],["issueNumber","additionalDetails"]],
"onepassword:index:GetCryptoWallet": [["notes"],["recoveryPhrase"],["password"],["walletAddress","wallet"]],
"onepassword:index:GetDriverLicense": [["notes"],["fullName"],["address"],["dateOfBirth"],["gender"],["height"],["number"],["licenseClass"],["conditionsRestrictions"],["state"],["country"],["expiryDate"]],
"onepassword:index:GetOutdoorLicense": [["notes"],["fullName"],["validFrom"],["expires"],["approvedWildlife"],["maximumQuota"],["state"],["country"]],
"onepassword:index:GetSocialSecurityNumber": [["notes"],["name"],["number"]],
"onepassword:index:GetAPICredential": [["notes"],["username"],["credential"],["type"],["filename"],["validFrom"],["expires"],["hostname"]],
"onepassword:index:GetDatabase": [["notes"],["type"],["server"],["port"],["database"],["username"],["password"],["sid"],["alias"],["connectionOptions"]],
"onepassword:index:GetLogin": [["username"],["password"],["notes"]],
"onepassword:index:GetMedicalRecord": [["notes"],["date"],["location"],["healthcareProfessional"],["patient"],["reasonForVisit"],["medication","medication"],["dosage","medication"],["medicationNotes","medication"]],
"onepassword:index:GetRewardProgram": [["notes"],["companyName"],["memberName"],["memberId"],["pin"],["memberIdAdditional","moreInformation"],["memberSince","moreInformation"],["customerServicePhone","moreInformation"],["phoneForReservations","moreInformation"],["website","moreInformation"]],
"onepassword:index:GetSecureNote": [["notes"]],
"onepassword:index:GetServer": [["notes"],["url"],["username"],["password"],["adminConsoleUrl","adminConsole"],["adminConsoleUsername","adminConsole"],["consolePassword","adminConsole"],["name","hostingProvider"],["website","hostingProvider"],["supportUrl","hostingProvider"],["supportPhone","hostingProvider"]],
"onepassword:index:GetSoftwareLicense": [["notes"],["version"],["licenseKey"],["licensedTo","customer"],["registeredEmail","customer"],["company","customer"],["downloadPage","publisher"],["publisher","publisher"],["website","publisher"],["retailPrice","publisher"],["supportEmail","publisher"],["purchaseDate","order"],["orderNumber","order"],["orderTotal","order"]],
"onepassword:index:GetBankAccount": [["notes"],["bankName"],["nameOnAccount"],["type"],["routingNumber"],["accountNumber"],["swift"],["iban"],["pin"],["phone","branchInformation"],["address","branchInformation"]],
"onepassword:index:GetEmailAccount": [["notes"],["type"],["username"],["server"],["portNumber"],["password"],["security"],["authMethod"],["smtpServer","smtp"],["portNumber","smtp"],["username","smtp"],["password","smtp"],["security","smtp"],["authMethod","smtp"],["provider","contactInformation"],["providersWebsite","contactInformation"],["phoneLocal","contactInformation"],["phoneTollFree","contactInformation"]]
}
