// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const Category = {
    ApiCredential: "API Credential",
    BankAccount: "Bank Account",
    CreditCard: "Credit Card",
    CryptoWallet: "Crypto Wallet",
    Database: "Database",
    Document: "Document",
    DriverLicense: "Driver License",
    EmailAccount: "Email Account",
    Identity: "Identity",
    Item: "Item",
    Item: "Item",
    Login: "Login",
    MedicalRecord: "Medical Record",
    Membership: "Membership",
    OutdoorLicense: "Outdoor License",
    Passport: "Passport",
    Password: "Password",
    RewardProgram: "Reward Program",
    SshKey: "SSH Key",
    SecureNote: "Secure Note",
    Server: "Server",
    SocialSecurityNumber: "Social Security Number",
    SoftwareLicense: "Software License",
    WirelessRouter: "Wireless Router",
} as const;

/**
 * The category of the item. One of [ApiCredential, BankAccount, CreditCard, CryptoWallet, Database, Document, DriverLicense, EmailAccount, Identity, Item, Login, MedicalRecord, Membership, OutdoorLicense, Passport, Password, RewardProgram, SecureNote, Server, SocialSecurityNumber, SoftwareLicense, SshKey, WirelessRouter]
 */
export type Category = (typeof Category)[keyof typeof Category];

export const FieldPurpose = {
    Username: "USERNAME",
    Password: "PASSWORD",
    Note: "NOTE",
} as const;

export type FieldPurpose = (typeof FieldPurpose)[keyof typeof FieldPurpose];
