// Code generated by Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package creditcard

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type AdditionalDetailsSection struct {
	CashWithdrawalLimit *string `pulumi:"cashWithdrawalLimit"`
	CreditLimit         *string `pulumi:"creditLimit"`
	InterestRate        *string `pulumi:"interestRate"`
	IssueNumber         *string `pulumi:"issueNumber"`
	Pin                 *string `pulumi:"pin"`
}

// AdditionalDetailsSectionInput is an input type that accepts AdditionalDetailsSectionArgs and AdditionalDetailsSectionOutput values.
// You can construct a concrete instance of `AdditionalDetailsSectionInput` via:
//
//	AdditionalDetailsSectionArgs{...}
type AdditionalDetailsSectionInput interface {
	pulumi.Input

	ToAdditionalDetailsSectionOutput() AdditionalDetailsSectionOutput
	ToAdditionalDetailsSectionOutputWithContext(context.Context) AdditionalDetailsSectionOutput
}

type AdditionalDetailsSectionArgs struct {
	CashWithdrawalLimit pulumi.StringPtrInput `pulumi:"cashWithdrawalLimit"`
	CreditLimit         pulumi.StringPtrInput `pulumi:"creditLimit"`
	InterestRate        pulumi.StringPtrInput `pulumi:"interestRate"`
	IssueNumber         pulumi.StringPtrInput `pulumi:"issueNumber"`
	Pin                 pulumi.StringPtrInput `pulumi:"pin"`
}

func (AdditionalDetailsSectionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*AdditionalDetailsSection)(nil)).Elem()
}

func (i AdditionalDetailsSectionArgs) ToAdditionalDetailsSectionOutput() AdditionalDetailsSectionOutput {
	return i.ToAdditionalDetailsSectionOutputWithContext(context.Background())
}

func (i AdditionalDetailsSectionArgs) ToAdditionalDetailsSectionOutputWithContext(ctx context.Context) AdditionalDetailsSectionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AdditionalDetailsSectionOutput)
}

func (i AdditionalDetailsSectionArgs) ToAdditionalDetailsSectionPtrOutput() AdditionalDetailsSectionPtrOutput {
	return i.ToAdditionalDetailsSectionPtrOutputWithContext(context.Background())
}

func (i AdditionalDetailsSectionArgs) ToAdditionalDetailsSectionPtrOutputWithContext(ctx context.Context) AdditionalDetailsSectionPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AdditionalDetailsSectionOutput).ToAdditionalDetailsSectionPtrOutputWithContext(ctx)
}

// AdditionalDetailsSectionPtrInput is an input type that accepts AdditionalDetailsSectionArgs, AdditionalDetailsSectionPtr and AdditionalDetailsSectionPtrOutput values.
// You can construct a concrete instance of `AdditionalDetailsSectionPtrInput` via:
//
//	        AdditionalDetailsSectionArgs{...}
//
//	or:
//
//	        nil
type AdditionalDetailsSectionPtrInput interface {
	pulumi.Input

	ToAdditionalDetailsSectionPtrOutput() AdditionalDetailsSectionPtrOutput
	ToAdditionalDetailsSectionPtrOutputWithContext(context.Context) AdditionalDetailsSectionPtrOutput
}

type additionalDetailsSectionPtrType AdditionalDetailsSectionArgs

func AdditionalDetailsSectionPtr(v *AdditionalDetailsSectionArgs) AdditionalDetailsSectionPtrInput {
	return (*additionalDetailsSectionPtrType)(v)
}

func (*additionalDetailsSectionPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**AdditionalDetailsSection)(nil)).Elem()
}

func (i *additionalDetailsSectionPtrType) ToAdditionalDetailsSectionPtrOutput() AdditionalDetailsSectionPtrOutput {
	return i.ToAdditionalDetailsSectionPtrOutputWithContext(context.Background())
}

func (i *additionalDetailsSectionPtrType) ToAdditionalDetailsSectionPtrOutputWithContext(ctx context.Context) AdditionalDetailsSectionPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AdditionalDetailsSectionPtrOutput)
}

type AdditionalDetailsSectionOutput struct{ *pulumi.OutputState }

func (AdditionalDetailsSectionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AdditionalDetailsSection)(nil)).Elem()
}

func (o AdditionalDetailsSectionOutput) ToAdditionalDetailsSectionOutput() AdditionalDetailsSectionOutput {
	return o
}

func (o AdditionalDetailsSectionOutput) ToAdditionalDetailsSectionOutputWithContext(ctx context.Context) AdditionalDetailsSectionOutput {
	return o
}

func (o AdditionalDetailsSectionOutput) ToAdditionalDetailsSectionPtrOutput() AdditionalDetailsSectionPtrOutput {
	return o.ToAdditionalDetailsSectionPtrOutputWithContext(context.Background())
}

func (o AdditionalDetailsSectionOutput) ToAdditionalDetailsSectionPtrOutputWithContext(ctx context.Context) AdditionalDetailsSectionPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v AdditionalDetailsSection) *AdditionalDetailsSection {
		return &v
	}).(AdditionalDetailsSectionPtrOutput)
}

func (o AdditionalDetailsSectionOutput) CashWithdrawalLimit() pulumi.StringPtrOutput {
	return o.ApplyT(func(v AdditionalDetailsSection) *string { return v.CashWithdrawalLimit }).(pulumi.StringPtrOutput)
}

func (o AdditionalDetailsSectionOutput) CreditLimit() pulumi.StringPtrOutput {
	return o.ApplyT(func(v AdditionalDetailsSection) *string { return v.CreditLimit }).(pulumi.StringPtrOutput)
}

func (o AdditionalDetailsSectionOutput) InterestRate() pulumi.StringPtrOutput {
	return o.ApplyT(func(v AdditionalDetailsSection) *string { return v.InterestRate }).(pulumi.StringPtrOutput)
}

func (o AdditionalDetailsSectionOutput) IssueNumber() pulumi.StringPtrOutput {
	return o.ApplyT(func(v AdditionalDetailsSection) *string { return v.IssueNumber }).(pulumi.StringPtrOutput)
}

func (o AdditionalDetailsSectionOutput) Pin() pulumi.StringPtrOutput {
	return o.ApplyT(func(v AdditionalDetailsSection) *string { return v.Pin }).(pulumi.StringPtrOutput)
}

type AdditionalDetailsSectionPtrOutput struct{ *pulumi.OutputState }

func (AdditionalDetailsSectionPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AdditionalDetailsSection)(nil)).Elem()
}

func (o AdditionalDetailsSectionPtrOutput) ToAdditionalDetailsSectionPtrOutput() AdditionalDetailsSectionPtrOutput {
	return o
}

func (o AdditionalDetailsSectionPtrOutput) ToAdditionalDetailsSectionPtrOutputWithContext(ctx context.Context) AdditionalDetailsSectionPtrOutput {
	return o
}

func (o AdditionalDetailsSectionPtrOutput) Elem() AdditionalDetailsSectionOutput {
	return o.ApplyT(func(v *AdditionalDetailsSection) AdditionalDetailsSection {
		if v != nil {
			return *v
		}
		var ret AdditionalDetailsSection
		return ret
	}).(AdditionalDetailsSectionOutput)
}

func (o AdditionalDetailsSectionPtrOutput) CashWithdrawalLimit() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AdditionalDetailsSection) *string {
		if v == nil {
			return nil
		}
		return v.CashWithdrawalLimit
	}).(pulumi.StringPtrOutput)
}

func (o AdditionalDetailsSectionPtrOutput) CreditLimit() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AdditionalDetailsSection) *string {
		if v == nil {
			return nil
		}
		return v.CreditLimit
	}).(pulumi.StringPtrOutput)
}

func (o AdditionalDetailsSectionPtrOutput) InterestRate() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AdditionalDetailsSection) *string {
		if v == nil {
			return nil
		}
		return v.InterestRate
	}).(pulumi.StringPtrOutput)
}

func (o AdditionalDetailsSectionPtrOutput) IssueNumber() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AdditionalDetailsSection) *string {
		if v == nil {
			return nil
		}
		return v.IssueNumber
	}).(pulumi.StringPtrOutput)
}

func (o AdditionalDetailsSectionPtrOutput) Pin() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AdditionalDetailsSection) *string {
		if v == nil {
			return nil
		}
		return v.Pin
	}).(pulumi.StringPtrOutput)
}

type ContactInformationSection struct {
	IssuingBank   *string `pulumi:"issuingBank"`
	PhoneIntl     *string `pulumi:"phoneIntl"`
	PhoneLocal    *string `pulumi:"phoneLocal"`
	PhoneTollFree *string `pulumi:"phoneTollFree"`
	Website       *string `pulumi:"website"`
}

// ContactInformationSectionInput is an input type that accepts ContactInformationSectionArgs and ContactInformationSectionOutput values.
// You can construct a concrete instance of `ContactInformationSectionInput` via:
//
//	ContactInformationSectionArgs{...}
type ContactInformationSectionInput interface {
	pulumi.Input

	ToContactInformationSectionOutput() ContactInformationSectionOutput
	ToContactInformationSectionOutputWithContext(context.Context) ContactInformationSectionOutput
}

type ContactInformationSectionArgs struct {
	IssuingBank   pulumi.StringPtrInput `pulumi:"issuingBank"`
	PhoneIntl     pulumi.StringPtrInput `pulumi:"phoneIntl"`
	PhoneLocal    pulumi.StringPtrInput `pulumi:"phoneLocal"`
	PhoneTollFree pulumi.StringPtrInput `pulumi:"phoneTollFree"`
	Website       pulumi.StringPtrInput `pulumi:"website"`
}

func (ContactInformationSectionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ContactInformationSection)(nil)).Elem()
}

func (i ContactInformationSectionArgs) ToContactInformationSectionOutput() ContactInformationSectionOutput {
	return i.ToContactInformationSectionOutputWithContext(context.Background())
}

func (i ContactInformationSectionArgs) ToContactInformationSectionOutputWithContext(ctx context.Context) ContactInformationSectionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ContactInformationSectionOutput)
}

func (i ContactInformationSectionArgs) ToContactInformationSectionPtrOutput() ContactInformationSectionPtrOutput {
	return i.ToContactInformationSectionPtrOutputWithContext(context.Background())
}

func (i ContactInformationSectionArgs) ToContactInformationSectionPtrOutputWithContext(ctx context.Context) ContactInformationSectionPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ContactInformationSectionOutput).ToContactInformationSectionPtrOutputWithContext(ctx)
}

// ContactInformationSectionPtrInput is an input type that accepts ContactInformationSectionArgs, ContactInformationSectionPtr and ContactInformationSectionPtrOutput values.
// You can construct a concrete instance of `ContactInformationSectionPtrInput` via:
//
//	        ContactInformationSectionArgs{...}
//
//	or:
//
//	        nil
type ContactInformationSectionPtrInput interface {
	pulumi.Input

	ToContactInformationSectionPtrOutput() ContactInformationSectionPtrOutput
	ToContactInformationSectionPtrOutputWithContext(context.Context) ContactInformationSectionPtrOutput
}

type contactInformationSectionPtrType ContactInformationSectionArgs

func ContactInformationSectionPtr(v *ContactInformationSectionArgs) ContactInformationSectionPtrInput {
	return (*contactInformationSectionPtrType)(v)
}

func (*contactInformationSectionPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ContactInformationSection)(nil)).Elem()
}

func (i *contactInformationSectionPtrType) ToContactInformationSectionPtrOutput() ContactInformationSectionPtrOutput {
	return i.ToContactInformationSectionPtrOutputWithContext(context.Background())
}

func (i *contactInformationSectionPtrType) ToContactInformationSectionPtrOutputWithContext(ctx context.Context) ContactInformationSectionPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ContactInformationSectionPtrOutput)
}

type ContactInformationSectionOutput struct{ *pulumi.OutputState }

func (ContactInformationSectionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ContactInformationSection)(nil)).Elem()
}

func (o ContactInformationSectionOutput) ToContactInformationSectionOutput() ContactInformationSectionOutput {
	return o
}

func (o ContactInformationSectionOutput) ToContactInformationSectionOutputWithContext(ctx context.Context) ContactInformationSectionOutput {
	return o
}

func (o ContactInformationSectionOutput) ToContactInformationSectionPtrOutput() ContactInformationSectionPtrOutput {
	return o.ToContactInformationSectionPtrOutputWithContext(context.Background())
}

func (o ContactInformationSectionOutput) ToContactInformationSectionPtrOutputWithContext(ctx context.Context) ContactInformationSectionPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ContactInformationSection) *ContactInformationSection {
		return &v
	}).(ContactInformationSectionPtrOutput)
}

func (o ContactInformationSectionOutput) IssuingBank() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ContactInformationSection) *string { return v.IssuingBank }).(pulumi.StringPtrOutput)
}

func (o ContactInformationSectionOutput) PhoneIntl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ContactInformationSection) *string { return v.PhoneIntl }).(pulumi.StringPtrOutput)
}

func (o ContactInformationSectionOutput) PhoneLocal() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ContactInformationSection) *string { return v.PhoneLocal }).(pulumi.StringPtrOutput)
}

func (o ContactInformationSectionOutput) PhoneTollFree() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ContactInformationSection) *string { return v.PhoneTollFree }).(pulumi.StringPtrOutput)
}

func (o ContactInformationSectionOutput) Website() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ContactInformationSection) *string { return v.Website }).(pulumi.StringPtrOutput)
}

type ContactInformationSectionPtrOutput struct{ *pulumi.OutputState }

func (ContactInformationSectionPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ContactInformationSection)(nil)).Elem()
}

func (o ContactInformationSectionPtrOutput) ToContactInformationSectionPtrOutput() ContactInformationSectionPtrOutput {
	return o
}

func (o ContactInformationSectionPtrOutput) ToContactInformationSectionPtrOutputWithContext(ctx context.Context) ContactInformationSectionPtrOutput {
	return o
}

func (o ContactInformationSectionPtrOutput) Elem() ContactInformationSectionOutput {
	return o.ApplyT(func(v *ContactInformationSection) ContactInformationSection {
		if v != nil {
			return *v
		}
		var ret ContactInformationSection
		return ret
	}).(ContactInformationSectionOutput)
}

func (o ContactInformationSectionPtrOutput) IssuingBank() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ContactInformationSection) *string {
		if v == nil {
			return nil
		}
		return v.IssuingBank
	}).(pulumi.StringPtrOutput)
}

func (o ContactInformationSectionPtrOutput) PhoneIntl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ContactInformationSection) *string {
		if v == nil {
			return nil
		}
		return v.PhoneIntl
	}).(pulumi.StringPtrOutput)
}

func (o ContactInformationSectionPtrOutput) PhoneLocal() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ContactInformationSection) *string {
		if v == nil {
			return nil
		}
		return v.PhoneLocal
	}).(pulumi.StringPtrOutput)
}

func (o ContactInformationSectionPtrOutput) PhoneTollFree() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ContactInformationSection) *string {
		if v == nil {
			return nil
		}
		return v.PhoneTollFree
	}).(pulumi.StringPtrOutput)
}

func (o ContactInformationSectionPtrOutput) Website() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ContactInformationSection) *string {
		if v == nil {
			return nil
		}
		return v.Website
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AdditionalDetailsSectionInput)(nil)).Elem(), AdditionalDetailsSectionArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*AdditionalDetailsSectionPtrInput)(nil)).Elem(), AdditionalDetailsSectionArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ContactInformationSectionInput)(nil)).Elem(), ContactInformationSectionArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ContactInformationSectionPtrInput)(nil)).Elem(), ContactInformationSectionArgs{})
	pulumi.RegisterOutputType(AdditionalDetailsSectionOutput{})
	pulumi.RegisterOutputType(AdditionalDetailsSectionPtrOutput{})
	pulumi.RegisterOutputType(ContactInformationSectionOutput{})
	pulumi.RegisterOutputType(ContactInformationSectionPtrOutput{})
}
