// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Rocket.Surgery.OnePasswordNativeUnoffical.Inputs
{

    public sealed class UrlArgs : Pulumi.ResourceArgs
    {
        [Input("href", required: true)]
        public Input<string> Href { get; set; } = null!;

        [Input("label")]
        public Input<string>? Label { get; set; }

        [Input("primary", required: true)]
        public Input<bool> Primary { get; set; } = null!;

        public UrlArgs()
        {
        }
    }
}
