// Code generated by Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cryptowallet

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type WalletSection struct {
	WalletAddress *string `pulumi:"walletAddress"`
}

// WalletSectionInput is an input type that accepts WalletSectionArgs and WalletSectionOutput values.
// You can construct a concrete instance of `WalletSectionInput` via:
//
//	WalletSectionArgs{...}
type WalletSectionInput interface {
	pulumi.Input

	ToWalletSectionOutput() WalletSectionOutput
	ToWalletSectionOutputWithContext(context.Context) WalletSectionOutput
}

type WalletSectionArgs struct {
	WalletAddress pulumi.StringPtrInput `pulumi:"walletAddress"`
}

func (WalletSectionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*WalletSection)(nil)).Elem()
}

func (i WalletSectionArgs) ToWalletSectionOutput() WalletSectionOutput {
	return i.ToWalletSectionOutputWithContext(context.Background())
}

func (i WalletSectionArgs) ToWalletSectionOutputWithContext(ctx context.Context) WalletSectionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WalletSectionOutput)
}

func (i WalletSectionArgs) ToWalletSectionPtrOutput() WalletSectionPtrOutput {
	return i.ToWalletSectionPtrOutputWithContext(context.Background())
}

func (i WalletSectionArgs) ToWalletSectionPtrOutputWithContext(ctx context.Context) WalletSectionPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WalletSectionOutput).ToWalletSectionPtrOutputWithContext(ctx)
}

// WalletSectionPtrInput is an input type that accepts WalletSectionArgs, WalletSectionPtr and WalletSectionPtrOutput values.
// You can construct a concrete instance of `WalletSectionPtrInput` via:
//
//	        WalletSectionArgs{...}
//
//	or:
//
//	        nil
type WalletSectionPtrInput interface {
	pulumi.Input

	ToWalletSectionPtrOutput() WalletSectionPtrOutput
	ToWalletSectionPtrOutputWithContext(context.Context) WalletSectionPtrOutput
}

type walletSectionPtrType WalletSectionArgs

func WalletSectionPtr(v *WalletSectionArgs) WalletSectionPtrInput {
	return (*walletSectionPtrType)(v)
}

func (*walletSectionPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**WalletSection)(nil)).Elem()
}

func (i *walletSectionPtrType) ToWalletSectionPtrOutput() WalletSectionPtrOutput {
	return i.ToWalletSectionPtrOutputWithContext(context.Background())
}

func (i *walletSectionPtrType) ToWalletSectionPtrOutputWithContext(ctx context.Context) WalletSectionPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WalletSectionPtrOutput)
}

type WalletSectionOutput struct{ *pulumi.OutputState }

func (WalletSectionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*WalletSection)(nil)).Elem()
}

func (o WalletSectionOutput) ToWalletSectionOutput() WalletSectionOutput {
	return o
}

func (o WalletSectionOutput) ToWalletSectionOutputWithContext(ctx context.Context) WalletSectionOutput {
	return o
}

func (o WalletSectionOutput) ToWalletSectionPtrOutput() WalletSectionPtrOutput {
	return o.ToWalletSectionPtrOutputWithContext(context.Background())
}

func (o WalletSectionOutput) ToWalletSectionPtrOutputWithContext(ctx context.Context) WalletSectionPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v WalletSection) *WalletSection {
		return &v
	}).(WalletSectionPtrOutput)
}

func (o WalletSectionOutput) WalletAddress() pulumi.StringPtrOutput {
	return o.ApplyT(func(v WalletSection) *string { return v.WalletAddress }).(pulumi.StringPtrOutput)
}

type WalletSectionPtrOutput struct{ *pulumi.OutputState }

func (WalletSectionPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**WalletSection)(nil)).Elem()
}

func (o WalletSectionPtrOutput) ToWalletSectionPtrOutput() WalletSectionPtrOutput {
	return o
}

func (o WalletSectionPtrOutput) ToWalletSectionPtrOutputWithContext(ctx context.Context) WalletSectionPtrOutput {
	return o
}

func (o WalletSectionPtrOutput) Elem() WalletSectionOutput {
	return o.ApplyT(func(v *WalletSection) WalletSection {
		if v != nil {
			return *v
		}
		var ret WalletSection
		return ret
	}).(WalletSectionOutput)
}

func (o WalletSectionPtrOutput) WalletAddress() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *WalletSection) *string {
		if v == nil {
			return nil
		}
		return v.WalletAddress
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*WalletSectionInput)(nil)).Elem(), WalletSectionArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*WalletSectionPtrInput)(nil)).Elem(), WalletSectionArgs{})
	pulumi.RegisterOutputType(WalletSectionOutput{})
	pulumi.RegisterOutputType(WalletSectionPtrOutput{})
}
