# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities
from . import outputs
from ._enums import *

__all__ = [
    'GetOutdoorLicenseResult',
    'AwaitableGetOutdoorLicenseResult',
    'get_outdoor_license',
    'get_outdoor_license_output',
]

@pulumi.output_type
class GetOutdoorLicenseResult:
    def __init__(__self__, approved_wildlife=None, attachments=None, category=None, country=None, expires=None, fields=None, full_name=None, maximum_quota=None, notes=None, references=None, sections=None, state=None, tags=None, title=None, uuid=None, valid_from=None, vault=None):
        if approved_wildlife and not isinstance(approved_wildlife, str):
            raise TypeError("Expected argument 'approved_wildlife' to be a str")
        pulumi.set(__self__, "approved_wildlife", approved_wildlife)
        if attachments and not isinstance(attachments, dict):
            raise TypeError("Expected argument 'attachments' to be a dict")
        pulumi.set(__self__, "attachments", attachments)
        if category and not isinstance(category, dict):
            raise TypeError("Expected argument 'category' to be a dict")
        pulumi.set(__self__, "category", category)
        if country and not isinstance(country, str):
            raise TypeError("Expected argument 'country' to be a str")
        pulumi.set(__self__, "country", country)
        if expires and not isinstance(expires, str):
            raise TypeError("Expected argument 'expires' to be a str")
        pulumi.set(__self__, "expires", expires)
        if fields and not isinstance(fields, dict):
            raise TypeError("Expected argument 'fields' to be a dict")
        pulumi.set(__self__, "fields", fields)
        if full_name and not isinstance(full_name, str):
            raise TypeError("Expected argument 'full_name' to be a str")
        pulumi.set(__self__, "full_name", full_name)
        if maximum_quota and not isinstance(maximum_quota, str):
            raise TypeError("Expected argument 'maximum_quota' to be a str")
        pulumi.set(__self__, "maximum_quota", maximum_quota)
        if notes and not isinstance(notes, str):
            raise TypeError("Expected argument 'notes' to be a str")
        pulumi.set(__self__, "notes", notes)
        if references and not isinstance(references, dict):
            raise TypeError("Expected argument 'references' to be a dict")
        pulumi.set(__self__, "references", references)
        if sections and not isinstance(sections, dict):
            raise TypeError("Expected argument 'sections' to be a dict")
        pulumi.set(__self__, "sections", sections)
        if state and not isinstance(state, str):
            raise TypeError("Expected argument 'state' to be a str")
        pulumi.set(__self__, "state", state)
        if tags and not isinstance(tags, list):
            raise TypeError("Expected argument 'tags' to be a list")
        pulumi.set(__self__, "tags", tags)
        if title and not isinstance(title, str):
            raise TypeError("Expected argument 'title' to be a str")
        pulumi.set(__self__, "title", title)
        if uuid and not isinstance(uuid, str):
            raise TypeError("Expected argument 'uuid' to be a str")
        pulumi.set(__self__, "uuid", uuid)
        if valid_from and not isinstance(valid_from, str):
            raise TypeError("Expected argument 'valid_from' to be a str")
        pulumi.set(__self__, "valid_from", valid_from)
        if vault and not isinstance(vault, str):
            raise TypeError("Expected argument 'vault' to be a str")
        pulumi.set(__self__, "vault", vault)

    @property
    @pulumi.getter(name="approvedWildlife")
    def approved_wildlife(self) -> Optional[str]:
        return pulumi.get(self, "approved_wildlife")

    @property
    @pulumi.getter
    def attachments(self) -> Mapping[str, 'outputs.OutField']:
        return pulumi.get(self, "attachments")

    @property
    @pulumi.getter
    def category(self) -> str:
        return pulumi.get(self, "category")

    @property
    @pulumi.getter
    def country(self) -> Optional[str]:
        return pulumi.get(self, "country")

    @property
    @pulumi.getter
    def expires(self) -> Optional[str]:
        return pulumi.get(self, "expires")

    @property
    @pulumi.getter
    def fields(self) -> Mapping[str, 'outputs.OutField']:
        return pulumi.get(self, "fields")

    @property
    @pulumi.getter(name="fullName")
    def full_name(self) -> Optional[str]:
        return pulumi.get(self, "full_name")

    @property
    @pulumi.getter(name="maximumQuota")
    def maximum_quota(self) -> Optional[str]:
        return pulumi.get(self, "maximum_quota")

    @property
    @pulumi.getter
    def notes(self) -> Optional[str]:
        return pulumi.get(self, "notes")

    @property
    @pulumi.getter
    def references(self) -> Mapping[str, 'outputs.OutField']:
        return pulumi.get(self, "references")

    @property
    @pulumi.getter
    def sections(self) -> Mapping[str, 'outputs.OutSection']:
        return pulumi.get(self, "sections")

    @property
    @pulumi.getter
    def state(self) -> Optional[str]:
        return pulumi.get(self, "state")

    @property
    @pulumi.getter
    def tags(self) -> Sequence[str]:
        """
        An array of strings of the tags assigned to the item.
        """
        return pulumi.get(self, "tags")

    @property
    @pulumi.getter
    def title(self) -> str:
        """
        The title of the item.
        """
        return pulumi.get(self, "title")

    @property
    @pulumi.getter
    def uuid(self) -> str:
        """
        The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
        """
        return pulumi.get(self, "uuid")

    @property
    @pulumi.getter(name="validFrom")
    def valid_from(self) -> Optional[str]:
        return pulumi.get(self, "valid_from")

    @property
    @pulumi.getter
    def vault(self) -> str:
        """
        The UUID of the vault the item is in.
        """
        return pulumi.get(self, "vault")


class AwaitableGetOutdoorLicenseResult(GetOutdoorLicenseResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetOutdoorLicenseResult(
            approved_wildlife=self.approved_wildlife,
            attachments=self.attachments,
            category=self.category,
            country=self.country,
            expires=self.expires,
            fields=self.fields,
            full_name=self.full_name,
            maximum_quota=self.maximum_quota,
            notes=self.notes,
            references=self.references,
            sections=self.sections,
            state=self.state,
            tags=self.tags,
            title=self.title,
            uuid=self.uuid,
            valid_from=self.valid_from,
            vault=self.vault)


def get_outdoor_license(title: Optional[str] = None,
                        uuid: Optional[str] = None,
                        vault: Optional[str] = None,
                        opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetOutdoorLicenseResult:
    """
    Use this data source to access information about an existing resource.

    :param str title: The title of the item to retrieve. This field will be populated with the title of the item if the item it looked up by its UUID.
    :param str uuid: The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
    :param str vault: The UUID of the vault the item is in.
    """
    __args__ = dict()
    __args__['title'] = title
    __args__['uuid'] = uuid
    __args__['vault'] = vault
    if opts is None:
        opts = pulumi.InvokeOptions()
    if opts.version is None:
        opts.version = _utilities.get_version()
    __ret__ = pulumi.runtime.invoke('one-password-native:index:GetOutdoorLicense', __args__, opts=opts, typ=GetOutdoorLicenseResult).value

    return AwaitableGetOutdoorLicenseResult(
        approved_wildlife=__ret__.approved_wildlife,
        attachments=__ret__.attachments,
        category=__ret__.category,
        country=__ret__.country,
        expires=__ret__.expires,
        fields=__ret__.fields,
        full_name=__ret__.full_name,
        maximum_quota=__ret__.maximum_quota,
        notes=__ret__.notes,
        references=__ret__.references,
        sections=__ret__.sections,
        state=__ret__.state,
        tags=__ret__.tags,
        title=__ret__.title,
        uuid=__ret__.uuid,
        valid_from=__ret__.valid_from,
        vault=__ret__.vault)


@_utilities.lift_output_func(get_outdoor_license)
def get_outdoor_license_output(title: Optional[pulumi.Input[Optional[str]]] = None,
                               uuid: Optional[pulumi.Input[Optional[str]]] = None,
                               vault: Optional[pulumi.Input[str]] = None,
                               opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetOutdoorLicenseResult]:
    """
    Use this data source to access information about an existing resource.

    :param str title: The title of the item to retrieve. This field will be populated with the title of the item if the item it looked up by its UUID.
    :param str uuid: The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
    :param str vault: The UUID of the vault the item is in.
    """
    ...
