// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi;

namespace Rocket.Surgery.OnePasswordNativeUnofficial
{
    public static class GetCreditCard
    {
        public static Task<GetCreditCardResult> InvokeAsync(GetCreditCardArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetCreditCardResult>("one-password-native-unofficial:index:GetCreditCard", args ?? new GetCreditCardArgs(), options.WithDefaults());

        public static Output<GetCreditCardResult> Invoke(GetCreditCardInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetCreditCardResult>("one-password-native-unofficial:index:GetCreditCard", args ?? new GetCreditCardInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetCreditCardArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
        /// </summary>
        [Input("id")]
        public string? Id { get; set; }

        /// <summary>
        /// The title of the item to retrieve. This field will be populated with the title of the item if the item it looked up by its UUID.
        /// </summary>
        [Input("title")]
        public string? Title { get; set; }

        /// <summary>
        /// The UUID of the vault the item is in.
        /// </summary>
        [Input("vault")]
        public string Vault { get; set; } = null!;

        public GetCreditCardArgs()
        {
        }
    }

    public sealed class GetCreditCardInvokeArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        /// <summary>
        /// The title of the item to retrieve. This field will be populated with the title of the item if the item it looked up by its UUID.
        /// </summary>
        [Input("title")]
        public Input<string>? Title { get; set; }

        /// <summary>
        /// The UUID of the vault the item is in.
        /// </summary>
        [Input("vault")]
        public Input<string> Vault { get; set; } = null!;

        public GetCreditCardInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetCreditCardResult
    {
        public readonly Rocket.Surgery.OnePasswordNativeUnofficial.CreditCard.Outputs.AdditionalDetailsSection? AdditionalDetails;
        public readonly ImmutableDictionary<string, Outputs.OutputAttachment> Attachments;
        public readonly string? CardholderName;
        public readonly string Category;
        public readonly Rocket.Surgery.OnePasswordNativeUnofficial.CreditCard.Outputs.ContactInformationSection? ContactInformation;
        public readonly string? ExpiryDate;
        public readonly ImmutableDictionary<string, Outputs.OutputField> Fields;
        /// <summary>
        /// The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
        /// </summary>
        public readonly string Id;
        public readonly string? Notes;
        public readonly string? Number;
        public readonly ImmutableArray<Outputs.OutputReference> References;
        public readonly ImmutableDictionary<string, Outputs.OutputSection> Sections;
        /// <summary>
        /// An array of strings of the tags assigned to the item.
        /// </summary>
        public readonly ImmutableArray<string> Tags;
        /// <summary>
        /// The title of the item.
        /// </summary>
        public readonly string Title;
        public readonly string? Type;
        public readonly ImmutableArray<Outputs.OutputUrl> Urls;
        public readonly string? ValidFrom;
        public readonly ImmutableDictionary<string, string> Vault;
        public readonly string? VerificationNumber;

        [OutputConstructor]
        private GetCreditCardResult(
            Rocket.Surgery.OnePasswordNativeUnofficial.CreditCard.Outputs.AdditionalDetailsSection? additionalDetails,

            ImmutableDictionary<string, Outputs.OutputAttachment> attachments,

            string? cardholderName,

            string category,

            Rocket.Surgery.OnePasswordNativeUnofficial.CreditCard.Outputs.ContactInformationSection? contactInformation,

            string? expiryDate,

            ImmutableDictionary<string, Outputs.OutputField> fields,

            string id,

            string? notes,

            string? number,

            ImmutableArray<Outputs.OutputReference> references,

            ImmutableDictionary<string, Outputs.OutputSection> sections,

            ImmutableArray<string> tags,

            string title,

            string? type,

            ImmutableArray<Outputs.OutputUrl> urls,

            string? validFrom,

            ImmutableDictionary<string, string> vault,

            string? verificationNumber)
        {
            AdditionalDetails = additionalDetails;
            Attachments = attachments;
            CardholderName = cardholderName;
            Category = category;
            ContactInformation = contactInformation;
            ExpiryDate = expiryDate;
            Fields = fields;
            Id = id;
            Notes = notes;
            Number = number;
            References = references;
            Sections = sections;
            Tags = tags;
            Title = title;
            Type = type;
            Urls = urls;
            ValidFrom = validFrom;
            Vault = vault;
            VerificationNumber = verificationNumber;
        }
    }
}
