// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Rocket.Surgery.OnePasswordNativeUnofficial
{
    public static class ReadBase64
    {
        public static Task<ReadBase64Result> InvokeAsync(ReadBase64Args args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<ReadBase64Result>("one-password-native-unofficial:index:ReadBase64", args ?? new ReadBase64Args(), options.WithDefaults());

        public static Output<ReadBase64Result> Invoke(ReadBase64InvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<ReadBase64Result>("one-password-native-unofficial:index:ReadBase64", args ?? new ReadBase64InvokeArgs(), options.WithDefaults());
    }


    public sealed class ReadBase64Args : Pulumi.InvokeArgs
    {
        /// <summary>
        /// The 1Password secret reference path to the attachment.  eg: op://vault/item/[section]/file 
        /// </summary>
        [Input("reference", required: true)]
        public string Reference { get; set; } = null!;

        public ReadBase64Args()
        {
        }
    }

    public sealed class ReadBase64InvokeArgs : Pulumi.InvokeArgs
    {
        /// <summary>
        /// The 1Password secret reference path to the attachment.  eg: op://vault/item/[section]/file 
        /// </summary>
        [Input("reference", required: true)]
        public Input<string> Reference { get; set; } = null!;

        public ReadBase64InvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class ReadBase64Result
    {
        /// <summary>
        /// The read value as a base64 encoded string
        /// </summary>
        public readonly string Base64;

        [OutputConstructor]
        private ReadBase64Result(string base64)
        {
            Base64 = base64;
        }
    }
}
