# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = [
    'Address',
    'Identification',
    'InternetDetails',
]

@pulumi.output_type
class Address(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "defaultPhone":
            suggest = "default_phone"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in Address. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        Address.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        Address.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 address: Optional[str] = None,
                 business: Optional[str] = None,
                 cell: Optional[str] = None,
                 default_phone: Optional[str] = None,
                 home: Optional[str] = None):
        if address is not None:
            pulumi.set(__self__, "address", address)
        if business is not None:
            pulumi.set(__self__, "business", business)
        if cell is not None:
            pulumi.set(__self__, "cell", cell)
        if default_phone is not None:
            pulumi.set(__self__, "default_phone", default_phone)
        if home is not None:
            pulumi.set(__self__, "home", home)

    @property
    @pulumi.getter
    def address(self) -> Optional[str]:
        return pulumi.get(self, "address")

    @property
    @pulumi.getter
    def business(self) -> Optional[str]:
        return pulumi.get(self, "business")

    @property
    @pulumi.getter
    def cell(self) -> Optional[str]:
        return pulumi.get(self, "cell")

    @property
    @pulumi.getter(name="defaultPhone")
    def default_phone(self) -> Optional[str]:
        return pulumi.get(self, "default_phone")

    @property
    @pulumi.getter
    def home(self) -> Optional[str]:
        return pulumi.get(self, "home")


@pulumi.output_type
class Identification(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "birthDate":
            suggest = "birth_date"
        elif key == "firstName":
            suggest = "first_name"
        elif key == "jobTitle":
            suggest = "job_title"
        elif key == "lastName":
            suggest = "last_name"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in Identification. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        Identification.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        Identification.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 birth_date: Optional[str] = None,
                 company: Optional[str] = None,
                 department: Optional[str] = None,
                 first_name: Optional[str] = None,
                 gender: Optional[str] = None,
                 initial: Optional[str] = None,
                 job_title: Optional[str] = None,
                 last_name: Optional[str] = None,
                 occupation: Optional[str] = None):
        if birth_date is not None:
            pulumi.set(__self__, "birth_date", birth_date)
        if company is not None:
            pulumi.set(__self__, "company", company)
        if department is not None:
            pulumi.set(__self__, "department", department)
        if first_name is not None:
            pulumi.set(__self__, "first_name", first_name)
        if gender is not None:
            pulumi.set(__self__, "gender", gender)
        if initial is not None:
            pulumi.set(__self__, "initial", initial)
        if job_title is not None:
            pulumi.set(__self__, "job_title", job_title)
        if last_name is not None:
            pulumi.set(__self__, "last_name", last_name)
        if occupation is not None:
            pulumi.set(__self__, "occupation", occupation)

    @property
    @pulumi.getter(name="birthDate")
    def birth_date(self) -> Optional[str]:
        return pulumi.get(self, "birth_date")

    @property
    @pulumi.getter
    def company(self) -> Optional[str]:
        return pulumi.get(self, "company")

    @property
    @pulumi.getter
    def department(self) -> Optional[str]:
        return pulumi.get(self, "department")

    @property
    @pulumi.getter(name="firstName")
    def first_name(self) -> Optional[str]:
        return pulumi.get(self, "first_name")

    @property
    @pulumi.getter
    def gender(self) -> Optional[str]:
        return pulumi.get(self, "gender")

    @property
    @pulumi.getter
    def initial(self) -> Optional[str]:
        return pulumi.get(self, "initial")

    @property
    @pulumi.getter(name="jobTitle")
    def job_title(self) -> Optional[str]:
        return pulumi.get(self, "job_title")

    @property
    @pulumi.getter(name="lastName")
    def last_name(self) -> Optional[str]:
        return pulumi.get(self, "last_name")

    @property
    @pulumi.getter
    def occupation(self) -> Optional[str]:
        return pulumi.get(self, "occupation")


@pulumi.output_type
class InternetDetails(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "aolAim":
            suggest = "aol_aim"
        elif key == "forumSignature":
            suggest = "forum_signature"
        elif key == "reminderAnswer":
            suggest = "reminder_answer"
        elif key == "reminderQuestion":
            suggest = "reminder_question"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in InternetDetails. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        InternetDetails.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        InternetDetails.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 aol_aim: Optional[str] = None,
                 email: Optional[str] = None,
                 forum_signature: Optional[str] = None,
                 icq: Optional[str] = None,
                 msn: Optional[str] = None,
                 reminder_answer: Optional[str] = None,
                 reminder_question: Optional[str] = None,
                 skype: Optional[str] = None,
                 username: Optional[str] = None,
                 website: Optional[str] = None,
                 yahoo: Optional[str] = None):
        if aol_aim is not None:
            pulumi.set(__self__, "aol_aim", aol_aim)
        if email is not None:
            pulumi.set(__self__, "email", email)
        if forum_signature is not None:
            pulumi.set(__self__, "forum_signature", forum_signature)
        if icq is not None:
            pulumi.set(__self__, "icq", icq)
        if msn is not None:
            pulumi.set(__self__, "msn", msn)
        if reminder_answer is not None:
            pulumi.set(__self__, "reminder_answer", reminder_answer)
        if reminder_question is not None:
            pulumi.set(__self__, "reminder_question", reminder_question)
        if skype is not None:
            pulumi.set(__self__, "skype", skype)
        if username is not None:
            pulumi.set(__self__, "username", username)
        if website is not None:
            pulumi.set(__self__, "website", website)
        if yahoo is not None:
            pulumi.set(__self__, "yahoo", yahoo)

    @property
    @pulumi.getter(name="aolAim")
    def aol_aim(self) -> Optional[str]:
        return pulumi.get(self, "aol_aim")

    @property
    @pulumi.getter
    def email(self) -> Optional[str]:
        return pulumi.get(self, "email")

    @property
    @pulumi.getter(name="forumSignature")
    def forum_signature(self) -> Optional[str]:
        return pulumi.get(self, "forum_signature")

    @property
    @pulumi.getter
    def icq(self) -> Optional[str]:
        return pulumi.get(self, "icq")

    @property
    @pulumi.getter
    def msn(self) -> Optional[str]:
        return pulumi.get(self, "msn")

    @property
    @pulumi.getter(name="reminderAnswer")
    def reminder_answer(self) -> Optional[str]:
        return pulumi.get(self, "reminder_answer")

    @property
    @pulumi.getter(name="reminderQuestion")
    def reminder_question(self) -> Optional[str]:
        return pulumi.get(self, "reminder_question")

    @property
    @pulumi.getter
    def skype(self) -> Optional[str]:
        return pulumi.get(self, "skype")

    @property
    @pulumi.getter
    def username(self) -> Optional[str]:
        return pulumi.get(self, "username")

    @property
    @pulumi.getter
    def website(self) -> Optional[str]:
        return pulumi.get(self, "website")

    @property
    @pulumi.getter
    def yahoo(self) -> Optional[str]:
        return pulumi.get(self, "yahoo")


