// Code generated by Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package onepassword

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-onepassword/sdk/go/onepassword/creditcard"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupCreditCard(ctx *pulumi.Context, args *LookupCreditCardArgs, opts ...pulumi.InvokeOption) (*LookupCreditCardResult, error) {
	var rv LookupCreditCardResult
	err := ctx.Invoke("onepassword:index:GetCreditCard", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupCreditCardArgs struct {
	// The title of the item to retrieve. This field will be populated with the title of the item if the item it looked up by its UUID.
	Title *string `pulumi:"title"`
	// The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
	Uuid *string `pulumi:"uuid"`
	// The UUID of the vault the item is in.
	Vault string `pulumi:"vault"`
}

type LookupCreditCardResult struct {
	AdditionalDetails  *creditcard.AdditionalDetails  `pulumi:"additionalDetails"`
	CardholderName     *string                        `pulumi:"cardholderName"`
	Category           *string                        `pulumi:"category"`
	ContactInformation *creditcard.ContactInformation `pulumi:"contactInformation"`
	ExpiryDate         *string                        `pulumi:"expiryDate"`
	Fields             []GetField                     `pulumi:"fields"`
	Id                 *string                        `pulumi:"id"`
	Notes              *string                        `pulumi:"notes"`
	Number             *string                        `pulumi:"number"`
	Sections           []GetSection                   `pulumi:"sections"`
	// An array of strings of the tags assigned to the item.
	Tags []string `pulumi:"tags"`
	// The title of the item.
	Title *string `pulumi:"title"`
	Type  *string `pulumi:"type"`
	// The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
	Uuid      *string `pulumi:"uuid"`
	ValidFrom *string `pulumi:"validFrom"`
	// The UUID of the vault the item is in.
	Vault              *string `pulumi:"vault"`
	VerificationNumber *string `pulumi:"verificationNumber"`
}

func LookupCreditCardOutput(ctx *pulumi.Context, args LookupCreditCardOutputArgs, opts ...pulumi.InvokeOption) LookupCreditCardResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupCreditCardResult, error) {
			args := v.(LookupCreditCardArgs)
			r, err := LookupCreditCard(ctx, &args, opts...)
			var s LookupCreditCardResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupCreditCardResultOutput)
}

type LookupCreditCardOutputArgs struct {
	// The title of the item to retrieve. This field will be populated with the title of the item if the item it looked up by its UUID.
	Title pulumi.StringPtrInput `pulumi:"title"`
	// The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
	Uuid pulumi.StringPtrInput `pulumi:"uuid"`
	// The UUID of the vault the item is in.
	Vault pulumi.StringInput `pulumi:"vault"`
}

func (LookupCreditCardOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCreditCardArgs)(nil)).Elem()
}

type LookupCreditCardResultOutput struct{ *pulumi.OutputState }

func (LookupCreditCardResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCreditCardResult)(nil)).Elem()
}

func (o LookupCreditCardResultOutput) ToLookupCreditCardResultOutput() LookupCreditCardResultOutput {
	return o
}

func (o LookupCreditCardResultOutput) ToLookupCreditCardResultOutputWithContext(ctx context.Context) LookupCreditCardResultOutput {
	return o
}

func (o LookupCreditCardResultOutput) AdditionalDetails() creditcard.AdditionalDetailsPtrOutput {
	return o.ApplyT(func(v LookupCreditCardResult) *creditcard.AdditionalDetails { return v.AdditionalDetails }).(creditcard.AdditionalDetailsPtrOutput)
}

func (o LookupCreditCardResultOutput) CardholderName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupCreditCardResult) *string { return v.CardholderName }).(pulumi.StringPtrOutput)
}

func (o LookupCreditCardResultOutput) Category() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupCreditCardResult) *string { return v.Category }).(pulumi.StringPtrOutput)
}

func (o LookupCreditCardResultOutput) ContactInformation() creditcard.ContactInformationPtrOutput {
	return o.ApplyT(func(v LookupCreditCardResult) *creditcard.ContactInformation { return v.ContactInformation }).(creditcard.ContactInformationPtrOutput)
}

func (o LookupCreditCardResultOutput) ExpiryDate() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupCreditCardResult) *string { return v.ExpiryDate }).(pulumi.StringPtrOutput)
}

func (o LookupCreditCardResultOutput) Fields() GetFieldArrayOutput {
	return o.ApplyT(func(v LookupCreditCardResult) []GetField { return v.Fields }).(GetFieldArrayOutput)
}

func (o LookupCreditCardResultOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupCreditCardResult) *string { return v.Id }).(pulumi.StringPtrOutput)
}

func (o LookupCreditCardResultOutput) Notes() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupCreditCardResult) *string { return v.Notes }).(pulumi.StringPtrOutput)
}

func (o LookupCreditCardResultOutput) Number() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupCreditCardResult) *string { return v.Number }).(pulumi.StringPtrOutput)
}

func (o LookupCreditCardResultOutput) Sections() GetSectionArrayOutput {
	return o.ApplyT(func(v LookupCreditCardResult) []GetSection { return v.Sections }).(GetSectionArrayOutput)
}

// An array of strings of the tags assigned to the item.
func (o LookupCreditCardResultOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupCreditCardResult) []string { return v.Tags }).(pulumi.StringArrayOutput)
}

// The title of the item.
func (o LookupCreditCardResultOutput) Title() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupCreditCardResult) *string { return v.Title }).(pulumi.StringPtrOutput)
}

func (o LookupCreditCardResultOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupCreditCardResult) *string { return v.Type }).(pulumi.StringPtrOutput)
}

// The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
func (o LookupCreditCardResultOutput) Uuid() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupCreditCardResult) *string { return v.Uuid }).(pulumi.StringPtrOutput)
}

func (o LookupCreditCardResultOutput) ValidFrom() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupCreditCardResult) *string { return v.ValidFrom }).(pulumi.StringPtrOutput)
}

// The UUID of the vault the item is in.
func (o LookupCreditCardResultOutput) Vault() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupCreditCardResult) *string { return v.Vault }).(pulumi.StringPtrOutput)
}

func (o LookupCreditCardResultOutput) VerificationNumber() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupCreditCardResult) *string { return v.VerificationNumber }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupCreditCardResultOutput{})
}
