// Code generated by Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package onepassword

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-onepassword/sdk/go/onepassword/emailaccount"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupEmailAccount(ctx *pulumi.Context, args *LookupEmailAccountArgs, opts ...pulumi.InvokeOption) (*LookupEmailAccountResult, error) {
	var rv LookupEmailAccountResult
	err := ctx.Invoke("onepassword:index:GetEmailAccount", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupEmailAccountArgs struct {
	// The title of the item to retrieve. This field will be populated with the title of the item if the item it looked up by its UUID.
	Title *string `pulumi:"title"`
	// The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
	Uuid *string `pulumi:"uuid"`
	// The UUID of the vault the item is in.
	Vault string `pulumi:"vault"`
}

type LookupEmailAccountResult struct {
	AuthMethod         *string                          `pulumi:"authMethod"`
	Category           *string                          `pulumi:"category"`
	ContactInformation *emailaccount.ContactInformation `pulumi:"contactInformation"`
	Fields             []GetField                       `pulumi:"fields"`
	Id                 *string                          `pulumi:"id"`
	Notes              *string                          `pulumi:"notes"`
	Password           *string                          `pulumi:"password"`
	PortNumber         *string                          `pulumi:"portNumber"`
	Sections           []GetSection                     `pulumi:"sections"`
	Security           *string                          `pulumi:"security"`
	Server             *string                          `pulumi:"server"`
	Smtp               *emailaccount.Smtp               `pulumi:"smtp"`
	// An array of strings of the tags assigned to the item.
	Tags []string `pulumi:"tags"`
	// The title of the item.
	Title    *string `pulumi:"title"`
	Type     *string `pulumi:"type"`
	Username *string `pulumi:"username"`
	// The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
	Uuid *string `pulumi:"uuid"`
	// The UUID of the vault the item is in.
	Vault *string `pulumi:"vault"`
}

func LookupEmailAccountOutput(ctx *pulumi.Context, args LookupEmailAccountOutputArgs, opts ...pulumi.InvokeOption) LookupEmailAccountResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupEmailAccountResult, error) {
			args := v.(LookupEmailAccountArgs)
			r, err := LookupEmailAccount(ctx, &args, opts...)
			var s LookupEmailAccountResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupEmailAccountResultOutput)
}

type LookupEmailAccountOutputArgs struct {
	// The title of the item to retrieve. This field will be populated with the title of the item if the item it looked up by its UUID.
	Title pulumi.StringPtrInput `pulumi:"title"`
	// The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
	Uuid pulumi.StringPtrInput `pulumi:"uuid"`
	// The UUID of the vault the item is in.
	Vault pulumi.StringInput `pulumi:"vault"`
}

func (LookupEmailAccountOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupEmailAccountArgs)(nil)).Elem()
}

type LookupEmailAccountResultOutput struct{ *pulumi.OutputState }

func (LookupEmailAccountResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupEmailAccountResult)(nil)).Elem()
}

func (o LookupEmailAccountResultOutput) ToLookupEmailAccountResultOutput() LookupEmailAccountResultOutput {
	return o
}

func (o LookupEmailAccountResultOutput) ToLookupEmailAccountResultOutputWithContext(ctx context.Context) LookupEmailAccountResultOutput {
	return o
}

func (o LookupEmailAccountResultOutput) AuthMethod() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupEmailAccountResult) *string { return v.AuthMethod }).(pulumi.StringPtrOutput)
}

func (o LookupEmailAccountResultOutput) Category() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupEmailAccountResult) *string { return v.Category }).(pulumi.StringPtrOutput)
}

func (o LookupEmailAccountResultOutput) ContactInformation() emailaccount.ContactInformationPtrOutput {
	return o.ApplyT(func(v LookupEmailAccountResult) *emailaccount.ContactInformation { return v.ContactInformation }).(emailaccount.ContactInformationPtrOutput)
}

func (o LookupEmailAccountResultOutput) Fields() GetFieldArrayOutput {
	return o.ApplyT(func(v LookupEmailAccountResult) []GetField { return v.Fields }).(GetFieldArrayOutput)
}

func (o LookupEmailAccountResultOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupEmailAccountResult) *string { return v.Id }).(pulumi.StringPtrOutput)
}

func (o LookupEmailAccountResultOutput) Notes() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupEmailAccountResult) *string { return v.Notes }).(pulumi.StringPtrOutput)
}

func (o LookupEmailAccountResultOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupEmailAccountResult) *string { return v.Password }).(pulumi.StringPtrOutput)
}

func (o LookupEmailAccountResultOutput) PortNumber() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupEmailAccountResult) *string { return v.PortNumber }).(pulumi.StringPtrOutput)
}

func (o LookupEmailAccountResultOutput) Sections() GetSectionArrayOutput {
	return o.ApplyT(func(v LookupEmailAccountResult) []GetSection { return v.Sections }).(GetSectionArrayOutput)
}

func (o LookupEmailAccountResultOutput) Security() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupEmailAccountResult) *string { return v.Security }).(pulumi.StringPtrOutput)
}

func (o LookupEmailAccountResultOutput) Server() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupEmailAccountResult) *string { return v.Server }).(pulumi.StringPtrOutput)
}

func (o LookupEmailAccountResultOutput) Smtp() emailaccount.SmtpPtrOutput {
	return o.ApplyT(func(v LookupEmailAccountResult) *emailaccount.Smtp { return v.Smtp }).(emailaccount.SmtpPtrOutput)
}

// An array of strings of the tags assigned to the item.
func (o LookupEmailAccountResultOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupEmailAccountResult) []string { return v.Tags }).(pulumi.StringArrayOutput)
}

// The title of the item.
func (o LookupEmailAccountResultOutput) Title() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupEmailAccountResult) *string { return v.Title }).(pulumi.StringPtrOutput)
}

func (o LookupEmailAccountResultOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupEmailAccountResult) *string { return v.Type }).(pulumi.StringPtrOutput)
}

func (o LookupEmailAccountResultOutput) Username() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupEmailAccountResult) *string { return v.Username }).(pulumi.StringPtrOutput)
}

// The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
func (o LookupEmailAccountResultOutput) Uuid() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupEmailAccountResult) *string { return v.Uuid }).(pulumi.StringPtrOutput)
}

// The UUID of the vault the item is in.
func (o LookupEmailAccountResultOutput) Vault() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupEmailAccountResult) *string { return v.Vault }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupEmailAccountResultOutput{})
}
