// Code generated by Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package onepassword

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupPassword(ctx *pulumi.Context, args *LookupPasswordArgs, opts ...pulumi.InvokeOption) (*LookupPasswordResult, error) {
	var rv LookupPasswordResult
	err := ctx.Invoke("onepassword:index:GetPassword", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupPasswordArgs struct {
	// The title of the item to retrieve. This field will be populated with the title of the item if the item it looked up by its UUID.
	Title *string `pulumi:"title"`
	// The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
	Uuid *string `pulumi:"uuid"`
	// The UUID of the vault the item is in.
	Vault string `pulumi:"vault"`
}

type LookupPasswordResult struct {
	Category *string      `pulumi:"category"`
	Fields   []GetField   `pulumi:"fields"`
	Id       *string      `pulumi:"id"`
	Notes    *string      `pulumi:"notes"`
	Password *string      `pulumi:"password"`
	Sections []GetSection `pulumi:"sections"`
	// An array of strings of the tags assigned to the item.
	Tags []string `pulumi:"tags"`
	// The title of the item.
	Title *string `pulumi:"title"`
	// The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
	Uuid *string `pulumi:"uuid"`
	// The UUID of the vault the item is in.
	Vault *string `pulumi:"vault"`
}

func LookupPasswordOutput(ctx *pulumi.Context, args LookupPasswordOutputArgs, opts ...pulumi.InvokeOption) LookupPasswordResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupPasswordResult, error) {
			args := v.(LookupPasswordArgs)
			r, err := LookupPassword(ctx, &args, opts...)
			var s LookupPasswordResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupPasswordResultOutput)
}

type LookupPasswordOutputArgs struct {
	// The title of the item to retrieve. This field will be populated with the title of the item if the item it looked up by its UUID.
	Title pulumi.StringPtrInput `pulumi:"title"`
	// The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
	Uuid pulumi.StringPtrInput `pulumi:"uuid"`
	// The UUID of the vault the item is in.
	Vault pulumi.StringInput `pulumi:"vault"`
}

func (LookupPasswordOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupPasswordArgs)(nil)).Elem()
}

type LookupPasswordResultOutput struct{ *pulumi.OutputState }

func (LookupPasswordResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupPasswordResult)(nil)).Elem()
}

func (o LookupPasswordResultOutput) ToLookupPasswordResultOutput() LookupPasswordResultOutput {
	return o
}

func (o LookupPasswordResultOutput) ToLookupPasswordResultOutputWithContext(ctx context.Context) LookupPasswordResultOutput {
	return o
}

func (o LookupPasswordResultOutput) Category() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupPasswordResult) *string { return v.Category }).(pulumi.StringPtrOutput)
}

func (o LookupPasswordResultOutput) Fields() GetFieldArrayOutput {
	return o.ApplyT(func(v LookupPasswordResult) []GetField { return v.Fields }).(GetFieldArrayOutput)
}

func (o LookupPasswordResultOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupPasswordResult) *string { return v.Id }).(pulumi.StringPtrOutput)
}

func (o LookupPasswordResultOutput) Notes() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupPasswordResult) *string { return v.Notes }).(pulumi.StringPtrOutput)
}

func (o LookupPasswordResultOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupPasswordResult) *string { return v.Password }).(pulumi.StringPtrOutput)
}

func (o LookupPasswordResultOutput) Sections() GetSectionArrayOutput {
	return o.ApplyT(func(v LookupPasswordResult) []GetSection { return v.Sections }).(GetSectionArrayOutput)
}

// An array of strings of the tags assigned to the item.
func (o LookupPasswordResultOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupPasswordResult) []string { return v.Tags }).(pulumi.StringArrayOutput)
}

// The title of the item.
func (o LookupPasswordResultOutput) Title() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupPasswordResult) *string { return v.Title }).(pulumi.StringPtrOutput)
}

// The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
func (o LookupPasswordResultOutput) Uuid() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupPasswordResult) *string { return v.Uuid }).(pulumi.StringPtrOutput)
}

// The UUID of the vault the item is in.
func (o LookupPasswordResultOutput) Vault() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupPasswordResult) *string { return v.Vault }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupPasswordResultOutput{})
}
