// Code generated by Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package onepassword

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupSecureNote(ctx *pulumi.Context, args *LookupSecureNoteArgs, opts ...pulumi.InvokeOption) (*LookupSecureNoteResult, error) {
	var rv LookupSecureNoteResult
	err := ctx.Invoke("onepassword:index:GetSecureNote", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupSecureNoteArgs struct {
	// The title of the item to retrieve. This field will be populated with the title of the item if the item it looked up by its UUID.
	Title *string `pulumi:"title"`
	// The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
	Uuid *string `pulumi:"uuid"`
	// The UUID of the vault the item is in.
	Vault string `pulumi:"vault"`
}

type LookupSecureNoteResult struct {
	Category *string      `pulumi:"category"`
	Fields   []GetField   `pulumi:"fields"`
	Id       *string      `pulumi:"id"`
	Notes    *string      `pulumi:"notes"`
	Sections []GetSection `pulumi:"sections"`
	// An array of strings of the tags assigned to the item.
	Tags []string `pulumi:"tags"`
	// The title of the item.
	Title *string `pulumi:"title"`
	// The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
	Uuid *string `pulumi:"uuid"`
	// The UUID of the vault the item is in.
	Vault *string `pulumi:"vault"`
}

func LookupSecureNoteOutput(ctx *pulumi.Context, args LookupSecureNoteOutputArgs, opts ...pulumi.InvokeOption) LookupSecureNoteResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupSecureNoteResult, error) {
			args := v.(LookupSecureNoteArgs)
			r, err := LookupSecureNote(ctx, &args, opts...)
			var s LookupSecureNoteResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupSecureNoteResultOutput)
}

type LookupSecureNoteOutputArgs struct {
	// The title of the item to retrieve. This field will be populated with the title of the item if the item it looked up by its UUID.
	Title pulumi.StringPtrInput `pulumi:"title"`
	// The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
	Uuid pulumi.StringPtrInput `pulumi:"uuid"`
	// The UUID of the vault the item is in.
	Vault pulumi.StringInput `pulumi:"vault"`
}

func (LookupSecureNoteOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSecureNoteArgs)(nil)).Elem()
}

type LookupSecureNoteResultOutput struct{ *pulumi.OutputState }

func (LookupSecureNoteResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSecureNoteResult)(nil)).Elem()
}

func (o LookupSecureNoteResultOutput) ToLookupSecureNoteResultOutput() LookupSecureNoteResultOutput {
	return o
}

func (o LookupSecureNoteResultOutput) ToLookupSecureNoteResultOutputWithContext(ctx context.Context) LookupSecureNoteResultOutput {
	return o
}

func (o LookupSecureNoteResultOutput) Category() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupSecureNoteResult) *string { return v.Category }).(pulumi.StringPtrOutput)
}

func (o LookupSecureNoteResultOutput) Fields() GetFieldArrayOutput {
	return o.ApplyT(func(v LookupSecureNoteResult) []GetField { return v.Fields }).(GetFieldArrayOutput)
}

func (o LookupSecureNoteResultOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupSecureNoteResult) *string { return v.Id }).(pulumi.StringPtrOutput)
}

func (o LookupSecureNoteResultOutput) Notes() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupSecureNoteResult) *string { return v.Notes }).(pulumi.StringPtrOutput)
}

func (o LookupSecureNoteResultOutput) Sections() GetSectionArrayOutput {
	return o.ApplyT(func(v LookupSecureNoteResult) []GetSection { return v.Sections }).(GetSectionArrayOutput)
}

// An array of strings of the tags assigned to the item.
func (o LookupSecureNoteResultOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupSecureNoteResult) []string { return v.Tags }).(pulumi.StringArrayOutput)
}

// The title of the item.
func (o LookupSecureNoteResultOutput) Title() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupSecureNoteResult) *string { return v.Title }).(pulumi.StringPtrOutput)
}

// The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
func (o LookupSecureNoteResultOutput) Uuid() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupSecureNoteResult) *string { return v.Uuid }).(pulumi.StringPtrOutput)
}

// The UUID of the vault the item is in.
func (o LookupSecureNoteResultOutput) Vault() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupSecureNoteResult) *string { return v.Vault }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSecureNoteResultOutput{})
}
