// Code generated by Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package emailaccount

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ContactInformationSection struct {
	PhoneLocal       *string `pulumi:"phoneLocal"`
	PhoneTollFree    *string `pulumi:"phoneTollFree"`
	Provider         *string `pulumi:"provider"`
	ProvidersWebsite *string `pulumi:"providersWebsite"`
}

// ContactInformationSectionInput is an input type that accepts ContactInformationSectionArgs and ContactInformationSectionOutput values.
// You can construct a concrete instance of `ContactInformationSectionInput` via:
//
//	ContactInformationSectionArgs{...}
type ContactInformationSectionInput interface {
	pulumi.Input

	ToContactInformationSectionOutput() ContactInformationSectionOutput
	ToContactInformationSectionOutputWithContext(context.Context) ContactInformationSectionOutput
}

type ContactInformationSectionArgs struct {
	PhoneLocal       pulumi.StringPtrInput `pulumi:"phoneLocal"`
	PhoneTollFree    pulumi.StringPtrInput `pulumi:"phoneTollFree"`
	Provider         pulumi.StringPtrInput `pulumi:"provider"`
	ProvidersWebsite pulumi.StringPtrInput `pulumi:"providersWebsite"`
}

func (ContactInformationSectionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ContactInformationSection)(nil)).Elem()
}

func (i ContactInformationSectionArgs) ToContactInformationSectionOutput() ContactInformationSectionOutput {
	return i.ToContactInformationSectionOutputWithContext(context.Background())
}

func (i ContactInformationSectionArgs) ToContactInformationSectionOutputWithContext(ctx context.Context) ContactInformationSectionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ContactInformationSectionOutput)
}

func (i ContactInformationSectionArgs) ToContactInformationSectionPtrOutput() ContactInformationSectionPtrOutput {
	return i.ToContactInformationSectionPtrOutputWithContext(context.Background())
}

func (i ContactInformationSectionArgs) ToContactInformationSectionPtrOutputWithContext(ctx context.Context) ContactInformationSectionPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ContactInformationSectionOutput).ToContactInformationSectionPtrOutputWithContext(ctx)
}

// ContactInformationSectionPtrInput is an input type that accepts ContactInformationSectionArgs, ContactInformationSectionPtr and ContactInformationSectionPtrOutput values.
// You can construct a concrete instance of `ContactInformationSectionPtrInput` via:
//
//	        ContactInformationSectionArgs{...}
//
//	or:
//
//	        nil
type ContactInformationSectionPtrInput interface {
	pulumi.Input

	ToContactInformationSectionPtrOutput() ContactInformationSectionPtrOutput
	ToContactInformationSectionPtrOutputWithContext(context.Context) ContactInformationSectionPtrOutput
}

type contactInformationSectionPtrType ContactInformationSectionArgs

func ContactInformationSectionPtr(v *ContactInformationSectionArgs) ContactInformationSectionPtrInput {
	return (*contactInformationSectionPtrType)(v)
}

func (*contactInformationSectionPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ContactInformationSection)(nil)).Elem()
}

func (i *contactInformationSectionPtrType) ToContactInformationSectionPtrOutput() ContactInformationSectionPtrOutput {
	return i.ToContactInformationSectionPtrOutputWithContext(context.Background())
}

func (i *contactInformationSectionPtrType) ToContactInformationSectionPtrOutputWithContext(ctx context.Context) ContactInformationSectionPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ContactInformationSectionPtrOutput)
}

type ContactInformationSectionOutput struct{ *pulumi.OutputState }

func (ContactInformationSectionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ContactInformationSection)(nil)).Elem()
}

func (o ContactInformationSectionOutput) ToContactInformationSectionOutput() ContactInformationSectionOutput {
	return o
}

func (o ContactInformationSectionOutput) ToContactInformationSectionOutputWithContext(ctx context.Context) ContactInformationSectionOutput {
	return o
}

func (o ContactInformationSectionOutput) ToContactInformationSectionPtrOutput() ContactInformationSectionPtrOutput {
	return o.ToContactInformationSectionPtrOutputWithContext(context.Background())
}

func (o ContactInformationSectionOutput) ToContactInformationSectionPtrOutputWithContext(ctx context.Context) ContactInformationSectionPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ContactInformationSection) *ContactInformationSection {
		return &v
	}).(ContactInformationSectionPtrOutput)
}

func (o ContactInformationSectionOutput) PhoneLocal() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ContactInformationSection) *string { return v.PhoneLocal }).(pulumi.StringPtrOutput)
}

func (o ContactInformationSectionOutput) PhoneTollFree() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ContactInformationSection) *string { return v.PhoneTollFree }).(pulumi.StringPtrOutput)
}

func (o ContactInformationSectionOutput) Provider() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ContactInformationSection) *string { return v.Provider }).(pulumi.StringPtrOutput)
}

func (o ContactInformationSectionOutput) ProvidersWebsite() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ContactInformationSection) *string { return v.ProvidersWebsite }).(pulumi.StringPtrOutput)
}

type ContactInformationSectionPtrOutput struct{ *pulumi.OutputState }

func (ContactInformationSectionPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ContactInformationSection)(nil)).Elem()
}

func (o ContactInformationSectionPtrOutput) ToContactInformationSectionPtrOutput() ContactInformationSectionPtrOutput {
	return o
}

func (o ContactInformationSectionPtrOutput) ToContactInformationSectionPtrOutputWithContext(ctx context.Context) ContactInformationSectionPtrOutput {
	return o
}

func (o ContactInformationSectionPtrOutput) Elem() ContactInformationSectionOutput {
	return o.ApplyT(func(v *ContactInformationSection) ContactInformationSection {
		if v != nil {
			return *v
		}
		var ret ContactInformationSection
		return ret
	}).(ContactInformationSectionOutput)
}

func (o ContactInformationSectionPtrOutput) PhoneLocal() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ContactInformationSection) *string {
		if v == nil {
			return nil
		}
		return v.PhoneLocal
	}).(pulumi.StringPtrOutput)
}

func (o ContactInformationSectionPtrOutput) PhoneTollFree() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ContactInformationSection) *string {
		if v == nil {
			return nil
		}
		return v.PhoneTollFree
	}).(pulumi.StringPtrOutput)
}

func (o ContactInformationSectionPtrOutput) Provider() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ContactInformationSection) *string {
		if v == nil {
			return nil
		}
		return v.Provider
	}).(pulumi.StringPtrOutput)
}

func (o ContactInformationSectionPtrOutput) ProvidersWebsite() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ContactInformationSection) *string {
		if v == nil {
			return nil
		}
		return v.ProvidersWebsite
	}).(pulumi.StringPtrOutput)
}

type SmtpSection struct {
	AuthMethod *string `pulumi:"authMethod"`
	Password   *string `pulumi:"password"`
	PortNumber *string `pulumi:"portNumber"`
	Security   *string `pulumi:"security"`
	SmtpServer *string `pulumi:"smtpServer"`
	Username   *string `pulumi:"username"`
}

// SmtpSectionInput is an input type that accepts SmtpSectionArgs and SmtpSectionOutput values.
// You can construct a concrete instance of `SmtpSectionInput` via:
//
//	SmtpSectionArgs{...}
type SmtpSectionInput interface {
	pulumi.Input

	ToSmtpSectionOutput() SmtpSectionOutput
	ToSmtpSectionOutputWithContext(context.Context) SmtpSectionOutput
}

type SmtpSectionArgs struct {
	AuthMethod pulumi.StringPtrInput `pulumi:"authMethod"`
	Password   pulumi.StringPtrInput `pulumi:"password"`
	PortNumber pulumi.StringPtrInput `pulumi:"portNumber"`
	Security   pulumi.StringPtrInput `pulumi:"security"`
	SmtpServer pulumi.StringPtrInput `pulumi:"smtpServer"`
	Username   pulumi.StringPtrInput `pulumi:"username"`
}

func (SmtpSectionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SmtpSection)(nil)).Elem()
}

func (i SmtpSectionArgs) ToSmtpSectionOutput() SmtpSectionOutput {
	return i.ToSmtpSectionOutputWithContext(context.Background())
}

func (i SmtpSectionArgs) ToSmtpSectionOutputWithContext(ctx context.Context) SmtpSectionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SmtpSectionOutput)
}

func (i SmtpSectionArgs) ToSmtpSectionPtrOutput() SmtpSectionPtrOutput {
	return i.ToSmtpSectionPtrOutputWithContext(context.Background())
}

func (i SmtpSectionArgs) ToSmtpSectionPtrOutputWithContext(ctx context.Context) SmtpSectionPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SmtpSectionOutput).ToSmtpSectionPtrOutputWithContext(ctx)
}

// SmtpSectionPtrInput is an input type that accepts SmtpSectionArgs, SmtpSectionPtr and SmtpSectionPtrOutput values.
// You can construct a concrete instance of `SmtpSectionPtrInput` via:
//
//	        SmtpSectionArgs{...}
//
//	or:
//
//	        nil
type SmtpSectionPtrInput interface {
	pulumi.Input

	ToSmtpSectionPtrOutput() SmtpSectionPtrOutput
	ToSmtpSectionPtrOutputWithContext(context.Context) SmtpSectionPtrOutput
}

type smtpSectionPtrType SmtpSectionArgs

func SmtpSectionPtr(v *SmtpSectionArgs) SmtpSectionPtrInput {
	return (*smtpSectionPtrType)(v)
}

func (*smtpSectionPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**SmtpSection)(nil)).Elem()
}

func (i *smtpSectionPtrType) ToSmtpSectionPtrOutput() SmtpSectionPtrOutput {
	return i.ToSmtpSectionPtrOutputWithContext(context.Background())
}

func (i *smtpSectionPtrType) ToSmtpSectionPtrOutputWithContext(ctx context.Context) SmtpSectionPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SmtpSectionPtrOutput)
}

type SmtpSectionOutput struct{ *pulumi.OutputState }

func (SmtpSectionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SmtpSection)(nil)).Elem()
}

func (o SmtpSectionOutput) ToSmtpSectionOutput() SmtpSectionOutput {
	return o
}

func (o SmtpSectionOutput) ToSmtpSectionOutputWithContext(ctx context.Context) SmtpSectionOutput {
	return o
}

func (o SmtpSectionOutput) ToSmtpSectionPtrOutput() SmtpSectionPtrOutput {
	return o.ToSmtpSectionPtrOutputWithContext(context.Background())
}

func (o SmtpSectionOutput) ToSmtpSectionPtrOutputWithContext(ctx context.Context) SmtpSectionPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v SmtpSection) *SmtpSection {
		return &v
	}).(SmtpSectionPtrOutput)
}

func (o SmtpSectionOutput) AuthMethod() pulumi.StringPtrOutput {
	return o.ApplyT(func(v SmtpSection) *string { return v.AuthMethod }).(pulumi.StringPtrOutput)
}

func (o SmtpSectionOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v SmtpSection) *string { return v.Password }).(pulumi.StringPtrOutput)
}

func (o SmtpSectionOutput) PortNumber() pulumi.StringPtrOutput {
	return o.ApplyT(func(v SmtpSection) *string { return v.PortNumber }).(pulumi.StringPtrOutput)
}

func (o SmtpSectionOutput) Security() pulumi.StringPtrOutput {
	return o.ApplyT(func(v SmtpSection) *string { return v.Security }).(pulumi.StringPtrOutput)
}

func (o SmtpSectionOutput) SmtpServer() pulumi.StringPtrOutput {
	return o.ApplyT(func(v SmtpSection) *string { return v.SmtpServer }).(pulumi.StringPtrOutput)
}

func (o SmtpSectionOutput) Username() pulumi.StringPtrOutput {
	return o.ApplyT(func(v SmtpSection) *string { return v.Username }).(pulumi.StringPtrOutput)
}

type SmtpSectionPtrOutput struct{ *pulumi.OutputState }

func (SmtpSectionPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SmtpSection)(nil)).Elem()
}

func (o SmtpSectionPtrOutput) ToSmtpSectionPtrOutput() SmtpSectionPtrOutput {
	return o
}

func (o SmtpSectionPtrOutput) ToSmtpSectionPtrOutputWithContext(ctx context.Context) SmtpSectionPtrOutput {
	return o
}

func (o SmtpSectionPtrOutput) Elem() SmtpSectionOutput {
	return o.ApplyT(func(v *SmtpSection) SmtpSection {
		if v != nil {
			return *v
		}
		var ret SmtpSection
		return ret
	}).(SmtpSectionOutput)
}

func (o SmtpSectionPtrOutput) AuthMethod() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SmtpSection) *string {
		if v == nil {
			return nil
		}
		return v.AuthMethod
	}).(pulumi.StringPtrOutput)
}

func (o SmtpSectionPtrOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SmtpSection) *string {
		if v == nil {
			return nil
		}
		return v.Password
	}).(pulumi.StringPtrOutput)
}

func (o SmtpSectionPtrOutput) PortNumber() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SmtpSection) *string {
		if v == nil {
			return nil
		}
		return v.PortNumber
	}).(pulumi.StringPtrOutput)
}

func (o SmtpSectionPtrOutput) Security() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SmtpSection) *string {
		if v == nil {
			return nil
		}
		return v.Security
	}).(pulumi.StringPtrOutput)
}

func (o SmtpSectionPtrOutput) SmtpServer() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SmtpSection) *string {
		if v == nil {
			return nil
		}
		return v.SmtpServer
	}).(pulumi.StringPtrOutput)
}

func (o SmtpSectionPtrOutput) Username() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SmtpSection) *string {
		if v == nil {
			return nil
		}
		return v.Username
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ContactInformationSectionInput)(nil)).Elem(), ContactInformationSectionArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ContactInformationSectionPtrInput)(nil)).Elem(), ContactInformationSectionArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*SmtpSectionInput)(nil)).Elem(), SmtpSectionArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*SmtpSectionPtrInput)(nil)).Elem(), SmtpSectionArgs{})
	pulumi.RegisterOutputType(ContactInformationSectionOutput{})
	pulumi.RegisterOutputType(ContactInformationSectionPtrOutput{})
	pulumi.RegisterOutputType(SmtpSectionOutput{})
	pulumi.RegisterOutputType(SmtpSectionPtrOutput{})
}
