// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs, enums } from "./types";
import * as utilities from "./utilities";

export function getDriverLicense(args: GetDriverLicenseArgs, opts?: pulumi.InvokeOptions): Promise<GetDriverLicenseResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("one-password-native-unoffical:index:GetDriverLicense", {
        "title": args.title,
        "uuid": args.uuid,
        "vault": args.vault,
    }, opts);
}

export interface GetDriverLicenseArgs {
    /**
     * The title of the item to retrieve. This field will be populated with the title of the item if the item it looked up by its UUID.
     */
    title?: string;
    /**
     * The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
     */
    uuid?: string;
    /**
     * The UUID of the vault the item is in.
     */
    vault: string;
}

export interface GetDriverLicenseResult {
    readonly address?: string;
    readonly attachments: {[key: string]: outputs.OutputAttachment};
    readonly category: enums.Category | string;
    readonly conditionsRestrictions?: string;
    readonly country?: string;
    readonly dateOfBirth?: string;
    readonly expiryDate?: string;
    readonly fields: {[key: string]: outputs.OutputField};
    readonly fullName?: string;
    readonly gender?: string;
    readonly height?: string;
    readonly licenseClass?: string;
    readonly notes?: string;
    readonly number?: string;
    readonly references: {[key: string]: outputs.OutputReference};
    readonly sections: {[key: string]: outputs.OutputSection};
    readonly state?: string;
    /**
     * An array of strings of the tags assigned to the item.
     */
    readonly tags: string[];
    /**
     * The title of the item.
     */
    readonly title: string;
    readonly urls?: outputs.OutputUrl[];
    /**
     * The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
     */
    readonly uuid: string;
    readonly vault: {[key: string]: string};
}

export function getDriverLicenseOutput(args: GetDriverLicenseOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDriverLicenseResult> {
    return pulumi.output(args).apply(a => getDriverLicense(a, opts))
}

export interface GetDriverLicenseOutputArgs {
    /**
     * The title of the item to retrieve. This field will be populated with the title of the item if the item it looked up by its UUID.
     */
    title?: pulumi.Input<string>;
    /**
     * The UUID of the item to retrieve. This field will be populated with the UUID of the item if the item it looked up by its title.
     */
    uuid?: pulumi.Input<string>;
    /**
     * The UUID of the vault the item is in.
     */
    vault: pulumi.Input<string>;
}
